<?php

namespace App\DataFixtures;

use App\Entity\Game\Achievement;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;

class AchievementFixtures extends Fixture
{
    public function load(ObjectManager $manager): void
    {
        $achievements = [
            // === COMBAT: Mobs tués par type ===
            // Slime
            ['slug' => 'kill-slime-10', 'title' => 'Nettoyeur de gelées', 'description' => 'Tuer 10 gelées', 'title_translations' => ['en' => 'Slime Cleaner'], 'description_translations' => ['en' => 'Kill 10 slimes'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'slime', 'count' => 10], 'reward' => ['gils' => 50]],
            ['slug' => 'kill-slime-50', 'title' => 'Chasseur de gelées', 'description' => 'Tuer 50 gelées', 'title_translations' => ['en' => 'Slime Hunter'], 'description_translations' => ['en' => 'Kill 50 slimes'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'slime', 'count' => 50], 'reward' => ['gils' => 200]],
            ['slug' => 'kill-slime-100', 'title' => 'Exterminateur de gelées', 'description' => 'Tuer 100 gelées', 'title_translations' => ['en' => 'Slime Exterminator'], 'description_translations' => ['en' => 'Kill 100 slimes'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'slime', 'count' => 100], 'reward' => ['gils' => 500, 'title' => 'Exterminateur de gelées']],
            // Goblin
            ['slug' => 'kill-goblin-10', 'title' => 'Nettoyeur de gobelins', 'description' => 'Tuer 10 gobelins', 'title_translations' => ['en' => 'Goblin Cleaner'], 'description_translations' => ['en' => 'Kill 10 goblins'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'goblin', 'count' => 10], 'reward' => ['gils' => 50]],
            ['slug' => 'kill-goblin-50', 'title' => 'Chasseur de gobelins', 'description' => 'Tuer 50 gobelins', 'title_translations' => ['en' => 'Goblin Hunter'], 'description_translations' => ['en' => 'Kill 50 goblins'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'goblin', 'count' => 50], 'reward' => ['gils' => 200]],
            ['slug' => 'kill-goblin-100', 'title' => 'Exterminateur de gobelins', 'description' => 'Tuer 100 gobelins', 'title_translations' => ['en' => 'Goblin Exterminator'], 'description_translations' => ['en' => 'Kill 100 goblins'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'goblin', 'count' => 100], 'reward' => ['gils' => 500, 'title' => 'Exterminateur de gobelins']],
            // Zombie
            ['slug' => 'kill-zombie-10', 'title' => 'Nettoyeur de zombies', 'description' => 'Tuer 10 zombies', 'title_translations' => ['en' => 'Zombie Cleaner'], 'description_translations' => ['en' => 'Kill 10 zombies'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'zombie', 'count' => 10], 'reward' => ['gils' => 75]],
            ['slug' => 'kill-zombie-50', 'title' => 'Chasseur de zombies', 'description' => 'Tuer 50 zombies', 'title_translations' => ['en' => 'Zombie Hunter'], 'description_translations' => ['en' => 'Kill 50 zombies'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'zombie', 'count' => 50], 'reward' => ['gils' => 250]],
            ['slug' => 'kill-zombie-100', 'title' => 'Exterminateur de zombies', 'description' => 'Tuer 100 zombies', 'title_translations' => ['en' => 'Zombie Exterminator'], 'description_translations' => ['en' => 'Kill 100 zombies'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'zombie', 'count' => 100], 'reward' => ['gils' => 600, 'title' => 'Exterminateur de zombies']],
            // Bat
            ['slug' => 'kill-bat-10', 'title' => 'Chasseur nocturne', 'description' => 'Tuer 10 chauves-souris', 'title_translations' => ['en' => 'Night Hunter'], 'description_translations' => ['en' => 'Kill 10 bats'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'bat', 'count' => 10], 'reward' => ['gils' => 50]],
            ['slug' => 'kill-bat-50', 'title' => 'Chasseur de chauves-souris', 'description' => 'Tuer 50 chauves-souris', 'title_translations' => ['en' => 'Bat Hunter'], 'description_translations' => ['en' => 'Kill 50 bats'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'bat', 'count' => 50], 'reward' => ['gils' => 200]],
            ['slug' => 'kill-bat-100', 'title' => 'Exterminateur de chauves-souris', 'description' => 'Tuer 100 chauves-souris', 'title_translations' => ['en' => 'Bat Exterminator'], 'description_translations' => ['en' => 'Kill 100 bats'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'bat', 'count' => 100], 'reward' => ['gils' => 500, 'title' => 'Exterminateur de chauves-souris']],
            // Giant rat
            ['slug' => 'kill-giant_rat-10', 'title' => 'Dératiseur', 'description' => 'Tuer 10 rats géants', 'title_translations' => ['en' => 'Rat Catcher'], 'description_translations' => ['en' => 'Kill 10 giant rats'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'giant_rat', 'count' => 10], 'reward' => ['gils' => 50]],
            ['slug' => 'kill-giant_rat-50', 'title' => 'Chasseur de rats', 'description' => 'Tuer 50 rats géants', 'title_translations' => ['en' => 'Rat Hunter'], 'description_translations' => ['en' => 'Kill 50 giant rats'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'giant_rat', 'count' => 50], 'reward' => ['gils' => 200]],
            ['slug' => 'kill-giant_rat-100', 'title' => 'Exterminateur de rats', 'description' => 'Tuer 100 rats géants', 'title_translations' => ['en' => 'Rat Exterminator'], 'description_translations' => ['en' => 'Kill 100 giant rats'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'giant_rat', 'count' => 100], 'reward' => ['gils' => 500, 'title' => 'Exterminateur de rats']],
            // Venom snake
            ['slug' => 'kill-venom_snake-10', 'title' => 'Tueur de serpents', 'description' => 'Tuer 10 serpents venimeux', 'title_translations' => ['en' => 'Snake Slayer'], 'description_translations' => ['en' => 'Kill 10 venomous snakes'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'venom_snake', 'count' => 10], 'reward' => ['gils' => 75]],
            ['slug' => 'kill-venom_snake-50', 'title' => 'Chasseur de serpents', 'description' => 'Tuer 50 serpents venimeux', 'title_translations' => ['en' => 'Snake Hunter'], 'description_translations' => ['en' => 'Kill 50 venomous snakes'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'venom_snake', 'count' => 50], 'reward' => ['gils' => 250]],
            ['slug' => 'kill-venom_snake-100', 'title' => 'Exterminateur de serpents', 'description' => 'Tuer 100 serpents venimeux', 'title_translations' => ['en' => 'Snake Exterminator'], 'description_translations' => ['en' => 'Kill 100 venomous snakes'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'venom_snake', 'count' => 100], 'reward' => ['gils' => 600, 'title' => 'Exterminateur de serpents']],
            // Wolf (tâche 140)
            ['slug' => 'kill-wolf-10', 'title' => 'Tueur de loups', 'description' => 'Tuer 10 loups', 'title_translations' => ['en' => 'Wolf Slayer'], 'description_translations' => ['en' => 'Kill 10 wolves'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'wolf', 'count' => 10], 'reward' => ['gils' => 50]],
            ['slug' => 'kill-wolf-50', 'title' => 'Chasseur de loups', 'description' => 'Tuer 50 loups', 'title_translations' => ['en' => 'Wolf Hunter'], 'description_translations' => ['en' => 'Kill 50 wolves'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'wolf', 'count' => 50], 'reward' => ['gils' => 200]],
            ['slug' => 'kill-wolf-100', 'title' => 'Exterminateur de loups', 'description' => 'Tuer 100 loups', 'title_translations' => ['en' => 'Wolf Exterminator'], 'description_translations' => ['en' => 'Kill 100 wolves'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'wolf', 'count' => 100], 'reward' => ['gils' => 500, 'title' => 'Exterminateur de loups']],
            // Scorpion (tâche 140)
            ['slug' => 'kill-scorpion-10', 'title' => 'Piqueur de scorpions', 'description' => 'Tuer 10 scorpions', 'title_translations' => ['en' => 'Scorpion Stinger'], 'description_translations' => ['en' => 'Kill 10 scorpions'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'scorpion', 'count' => 10], 'reward' => ['gils' => 75]],
            ['slug' => 'kill-scorpion-50', 'title' => 'Chasseur de scorpions', 'description' => 'Tuer 50 scorpions', 'title_translations' => ['en' => 'Scorpion Hunter'], 'description_translations' => ['en' => 'Kill 50 scorpions'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'scorpion', 'count' => 50], 'reward' => ['gils' => 250]],
            ['slug' => 'kill-scorpion-100', 'title' => 'Exterminateur de scorpions', 'description' => 'Tuer 100 scorpions', 'title_translations' => ['en' => 'Scorpion Exterminator'], 'description_translations' => ['en' => 'Kill 100 scorpions'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'scorpion', 'count' => 100], 'reward' => ['gils' => 600, 'title' => 'Exterminateur de scorpions']],
            // Beetle (tâche 140)
            ['slug' => 'kill-beetle-10', 'title' => 'Écraseur de scarabées', 'description' => 'Tuer 10 scarabées', 'title_translations' => ['en' => 'Beetle Crusher'], 'description_translations' => ['en' => 'Kill 10 beetles'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'beetle', 'count' => 10], 'reward' => ['gils' => 50]],
            ['slug' => 'kill-beetle-50', 'title' => 'Chasseur de scarabées', 'description' => 'Tuer 50 scarabées', 'title_translations' => ['en' => 'Beetle Hunter'], 'description_translations' => ['en' => 'Kill 50 beetles'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'beetle', 'count' => 50], 'reward' => ['gils' => 200]],
            ['slug' => 'kill-beetle-100', 'title' => 'Exterminateur de scarabées', 'description' => 'Tuer 100 scarabées', 'title_translations' => ['en' => 'Beetle Exterminator'], 'description_translations' => ['en' => 'Kill 100 beetles'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'beetle', 'count' => 100], 'reward' => ['gils' => 500, 'title' => 'Exterminateur de scarabées']],
            // Mushroom golem (tâche 140)
            ['slug' => 'kill-mushroom_golem-10', 'title' => 'Cueilleur de champignons', 'description' => 'Tuer 10 golems champignons', 'title_translations' => ['en' => 'Mushroom Picker'], 'description_translations' => ['en' => 'Kill 10 mushroom golems'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'mushroom_golem', 'count' => 10], 'reward' => ['gils' => 75]],
            ['slug' => 'kill-mushroom_golem-50', 'title' => 'Chasseur de champignons', 'description' => 'Tuer 50 golems champignons', 'title_translations' => ['en' => 'Mushroom Hunter'], 'description_translations' => ['en' => 'Kill 50 mushroom golems'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'mushroom_golem', 'count' => 50], 'reward' => ['gils' => 250]],
            ['slug' => 'kill-mushroom_golem-100', 'title' => 'Exterminateur de champignons', 'description' => 'Tuer 100 golems champignons', 'title_translations' => ['en' => 'Mushroom Exterminator'], 'description_translations' => ['en' => 'Kill 100 mushroom golems'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'mushroom_golem', 'count' => 100], 'reward' => ['gils' => 600, 'title' => 'Exterminateur de champignons']],
            // Ghost (tâche 140)
            ['slug' => 'kill-ghost-10', 'title' => 'Chasseur de fantômes', 'description' => 'Tuer 10 fantômes', 'title_translations' => ['en' => 'Ghost Hunter'], 'description_translations' => ['en' => 'Kill 10 ghosts'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'ghost', 'count' => 10], 'reward' => ['gils' => 75]],
            ['slug' => 'kill-ghost-50', 'title' => 'Exorciste', 'description' => 'Tuer 50 fantômes', 'title_translations' => ['en' => 'Exorcist'], 'description_translations' => ['en' => 'Kill 50 ghosts'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'ghost', 'count' => 50], 'reward' => ['gils' => 250]],
            ['slug' => 'kill-ghost-100', 'title' => 'Exterminateur de fantômes', 'description' => 'Tuer 100 fantômes', 'title_translations' => ['en' => 'Ghost Exterminator'], 'description_translations' => ['en' => 'Kill 100 ghosts'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'ghost', 'count' => 100], 'reward' => ['gils' => 600, 'title' => 'Exterminateur de fantômes']],
            // Skeleton
            ['slug' => 'kill-skeleton-10', 'title' => 'Briseur d\'os', 'description' => 'Tuer 10 squelettes', 'title_translations' => ['en' => 'Bone Breaker'], 'description_translations' => ['en' => 'Kill 10 skeletons'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'skeleton', 'count' => 10], 'reward' => ['gils' => 75]],
            ['slug' => 'kill-skeleton-50', 'title' => 'Chasseur de squelettes', 'description' => 'Tuer 50 squelettes', 'title_translations' => ['en' => 'Skeleton Hunter'], 'description_translations' => ['en' => 'Kill 50 skeletons'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'skeleton', 'count' => 50], 'reward' => ['gils' => 250]],
            ['slug' => 'kill-skeleton-100', 'title' => 'Exterminateur de squelettes', 'description' => 'Tuer 100 squelettes', 'title_translations' => ['en' => 'Skeleton Exterminator'], 'description_translations' => ['en' => 'Kill 100 skeletons'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'skeleton', 'count' => 100], 'reward' => ['gils' => 600, 'title' => 'Exterminateur de squelettes']],
            // Spider
            ['slug' => 'kill-spider-10', 'title' => 'Arachnophobe', 'description' => 'Tuer 10 araignées', 'title_translations' => ['en' => 'Arachnophobe'], 'description_translations' => ['en' => 'Kill 10 spiders'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'spider', 'count' => 10], 'reward' => ['gils' => 100]],
            ['slug' => 'kill-spider-50', 'title' => 'Chasseur d\'araignées', 'description' => 'Tuer 50 araignées', 'title_translations' => ['en' => 'Spider Hunter'], 'description_translations' => ['en' => 'Kill 50 spiders'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'spider', 'count' => 50], 'reward' => ['gils' => 300]],
            ['slug' => 'kill-spider-100', 'title' => 'Exterminateur d\'araignées', 'description' => 'Tuer 100 araignées', 'title_translations' => ['en' => 'Spider Exterminator'], 'description_translations' => ['en' => 'Kill 100 spiders'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'spider', 'count' => 100], 'reward' => ['gils' => 700, 'title' => 'Exterminateur d\'araignées']],
            // Troll
            ['slug' => 'kill-troll-10', 'title' => 'Tueur de trolls', 'description' => 'Tuer 10 trolls', 'title_translations' => ['en' => 'Troll Slayer'], 'description_translations' => ['en' => 'Kill 10 trolls'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'troll', 'count' => 10], 'reward' => ['gils' => 200]],
            ['slug' => 'kill-troll-50', 'title' => 'Chasseur de trolls', 'description' => 'Tuer 50 trolls', 'title_translations' => ['en' => 'Troll Hunter'], 'description_translations' => ['en' => 'Kill 50 trolls'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'troll', 'count' => 50], 'reward' => ['gils' => 500]],
            ['slug' => 'kill-troll-100', 'title' => 'Exterminateur de trolls', 'description' => 'Tuer 100 trolls', 'title_translations' => ['en' => 'Troll Exterminator'], 'description_translations' => ['en' => 'Kill 100 trolls'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'troll', 'count' => 100], 'reward' => ['gils' => 1000, 'title' => 'Exterminateur de trolls']],
            // Werewolf
            ['slug' => 'kill-werewolf-10', 'title' => 'Tueur de loups-garous', 'description' => 'Tuer 10 loups-garous', 'title_translations' => ['en' => 'Werewolf Slayer'], 'description_translations' => ['en' => 'Kill 10 werewolves'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'werewolf', 'count' => 10], 'reward' => ['gils' => 150]],
            ['slug' => 'kill-werewolf-50', 'title' => 'Chasseur de loups-garous', 'description' => 'Tuer 50 loups-garous', 'title_translations' => ['en' => 'Werewolf Hunter'], 'description_translations' => ['en' => 'Kill 50 werewolves'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'werewolf', 'count' => 50], 'reward' => ['gils' => 400]],
            ['slug' => 'kill-werewolf-100', 'title' => 'Exterminateur de loups-garous', 'description' => 'Tuer 100 loups-garous', 'title_translations' => ['en' => 'Werewolf Exterminator'], 'description_translations' => ['en' => 'Kill 100 werewolves'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'werewolf', 'count' => 100], 'reward' => ['gils' => 800, 'title' => 'Exterminateur de loups-garous']],
            // Dragon
            ['slug' => 'kill-dragon-10', 'title' => 'Tueur de dragons', 'description' => 'Tuer 10 dragons', 'title_translations' => ['en' => 'Dragon Slayer'], 'description_translations' => ['en' => 'Kill 10 dragons'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'dragon', 'count' => 10], 'reward' => ['gils' => 500]],
            ['slug' => 'kill-dragon-50', 'title' => 'Chasseur de dragons', 'description' => 'Tuer 50 dragons', 'title_translations' => ['en' => 'Dragon Hunter'], 'description_translations' => ['en' => 'Kill 50 dragons'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'dragon', 'count' => 50], 'reward' => ['gils' => 1500]],
            ['slug' => 'kill-dragon-100', 'title' => 'Pourfendeur de dragons', 'description' => 'Tuer 100 dragons', 'title_translations' => ['en' => 'Dragonbane'], 'description_translations' => ['en' => 'Kill 100 dragons'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'dragon', 'count' => 100], 'reward' => ['gils' => 5000, 'title' => 'Pourfendeur de dragons']],

            // Salamandre
            ['slug' => 'kill-salamander-10', 'title' => 'Chasseur de flammes', 'description' => 'Tuer 10 salamandres', 'title_translations' => ['en' => 'Flame Hunter'], 'description_translations' => ['en' => 'Kill 10 salamanders'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'salamander', 'count' => 10], 'reward' => ['gils' => 100]],
            ['slug' => 'kill-salamander-50', 'title' => 'Dompteur de salamandres', 'description' => 'Tuer 50 salamandres', 'title_translations' => ['en' => 'Salamander Tamer'], 'description_translations' => ['en' => 'Kill 50 salamanders'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'salamander', 'count' => 50], 'reward' => ['gils' => 300]],
            ['slug' => 'kill-salamander-100', 'title' => 'Exterminateur de salamandres', 'description' => 'Tuer 100 salamandres', 'title_translations' => ['en' => 'Salamander Exterminator'], 'description_translations' => ['en' => 'Kill 100 salamanders'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'salamander', 'count' => 100], 'reward' => ['gils' => 700, 'title' => 'Exterminateur de salamandres']],
            // Ondine
            ['slug' => 'kill-undine-10', 'title' => 'Pêcheur d\'ondines', 'description' => 'Tuer 10 ondines', 'title_translations' => ['en' => 'Undine Fisher'], 'description_translations' => ['en' => 'Kill 10 undines'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'undine', 'count' => 10], 'reward' => ['gils' => 75]],
            ['slug' => 'kill-undine-50', 'title' => 'Chasseur d\'ondines', 'description' => 'Tuer 50 ondines', 'title_translations' => ['en' => 'Undine Hunter'], 'description_translations' => ['en' => 'Kill 50 undines'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'undine', 'count' => 50], 'reward' => ['gils' => 250]],
            ['slug' => 'kill-undine-100', 'title' => 'Exterminateur d\'ondines', 'description' => 'Tuer 100 ondines', 'title_translations' => ['en' => 'Undine Exterminator'], 'description_translations' => ['en' => 'Kill 100 undines'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'undine', 'count' => 100], 'reward' => ['gils' => 600, 'title' => 'Exterminateur d\'ondines']],
            // Sylphe
            ['slug' => 'kill-sylph-10', 'title' => 'Briseur de vents', 'description' => 'Tuer 10 sylphes', 'title_translations' => ['en' => 'Wind Breaker'], 'description_translations' => ['en' => 'Kill 10 sylphs'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'sylph', 'count' => 10], 'reward' => ['gils' => 150]],
            ['slug' => 'kill-sylph-50', 'title' => 'Chasseur de sylphes', 'description' => 'Tuer 50 sylphes', 'title_translations' => ['en' => 'Sylph Hunter'], 'description_translations' => ['en' => 'Kill 50 sylphs'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'sylph', 'count' => 50], 'reward' => ['gils' => 400]],
            ['slug' => 'kill-sylph-100', 'title' => 'Exterminateur de sylphes', 'description' => 'Tuer 100 sylphes', 'title_translations' => ['en' => 'Sylph Exterminator'], 'description_translations' => ['en' => 'Kill 100 sylphs'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'sylph', 'count' => 100], 'reward' => ['gils' => 800, 'title' => 'Exterminateur de sylphes']],
            // Golem d'argile
            ['slug' => 'kill-clay-golem-10', 'title' => 'Briseur de golems', 'description' => 'Tuer 10 golems d\'argile', 'title_translations' => ['en' => 'Golem Breaker'], 'description_translations' => ['en' => 'Kill 10 clay golems'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'clay_golem', 'count' => 10], 'reward' => ['gils' => 200]],
            ['slug' => 'kill-clay-golem-50', 'title' => 'Chasseur de golems d\'argile', 'description' => 'Tuer 50 golems d\'argile', 'title_translations' => ['en' => 'Clay Golem Hunter'], 'description_translations' => ['en' => 'Kill 50 clay golems'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'clay_golem', 'count' => 50], 'reward' => ['gils' => 500]],
            ['slug' => 'kill-clay-golem-100', 'title' => 'Exterminateur de golems d\'argile', 'description' => 'Tuer 100 golems d\'argile', 'title_translations' => ['en' => 'Clay Golem Exterminator'], 'description_translations' => ['en' => 'Kill 100 clay golems'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'clay_golem', 'count' => 100], 'reward' => ['gils' => 1000, 'title' => 'Exterminateur de golems d\'argile']],
            // Automate rouillé
            ['slug' => 'kill-rusty-automaton-10', 'title' => 'Ferrailleur', 'description' => 'Tuer 10 automates rouillés', 'title_translations' => ['en' => 'Scrapper'], 'description_translations' => ['en' => 'Kill 10 rusty automatons'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'rusty_automaton', 'count' => 10], 'reward' => ['gils' => 100]],
            ['slug' => 'kill-rusty-automaton-50', 'title' => 'Chasseur d\'automates', 'description' => 'Tuer 50 automates rouillés', 'title_translations' => ['en' => 'Automaton Hunter'], 'description_translations' => ['en' => 'Kill 50 rusty automatons'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'rusty_automaton', 'count' => 50], 'reward' => ['gils' => 300]],
            ['slug' => 'kill-rusty-automaton-100', 'title' => 'Exterminateur d\'automates', 'description' => 'Tuer 100 automates rouillés', 'title_translations' => ['en' => 'Automaton Exterminator'], 'description_translations' => ['en' => 'Kill 100 rusty automatons'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'rusty_automaton', 'count' => 100], 'reward' => ['gils' => 700, 'title' => 'Exterminateur d\'automates']],
            // Loup alpha
            ['slug' => 'kill-alpha-wolf-10', 'title' => 'Tueur de meute', 'description' => 'Tuer 10 loups alpha', 'title_translations' => ['en' => 'Pack Slayer'], 'description_translations' => ['en' => 'Kill 10 alpha wolves'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'alpha_wolf', 'count' => 10], 'reward' => ['gils' => 150]],
            ['slug' => 'kill-alpha-wolf-50', 'title' => 'Chasseur de loups alpha', 'description' => 'Tuer 50 loups alpha', 'title_translations' => ['en' => 'Alpha Wolf Hunter'], 'description_translations' => ['en' => 'Kill 50 alpha wolves'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'alpha_wolf', 'count' => 50], 'reward' => ['gils' => 400]],
            ['slug' => 'kill-alpha-wolf-100', 'title' => 'Exterminateur de loups alpha', 'description' => 'Tuer 100 loups alpha', 'title_translations' => ['en' => 'Alpha Wolf Exterminator'], 'description_translations' => ['en' => 'Kill 100 alpha wolves'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'alpha_wolf', 'count' => 100], 'reward' => ['gils' => 800, 'title' => 'Exterminateur de loups alpha']],
            // Feu follet
            ['slug' => 'kill-will-o-wisp-10', 'title' => 'Chasseur de lumières', 'description' => 'Tuer 10 feux follets', 'title_translations' => ['en' => 'Light Chaser'], 'description_translations' => ['en' => 'Kill 10 will-o-the-wisps'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'will_o_wisp', 'count' => 10], 'reward' => ['gils' => 75]],
            ['slug' => 'kill-will-o-wisp-50', 'title' => 'Éteigneur de feux follets', 'description' => 'Tuer 50 feux follets', 'title_translations' => ['en' => 'Wisp Snuffer'], 'description_translations' => ['en' => 'Kill 50 will-o-the-wisps'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'will_o_wisp', 'count' => 50], 'reward' => ['gils' => 250]],
            ['slug' => 'kill-will-o-wisp-100', 'title' => 'Exterminateur de feux follets', 'description' => 'Tuer 100 feux follets', 'title_translations' => ['en' => 'Wisp Exterminator'], 'description_translations' => ['en' => 'Kill 100 will-o-the-wisps'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'will_o_wisp', 'count' => 100], 'reward' => ['gils' => 600, 'title' => 'Exterminateur de feux follets']],
            // Ombre rampante
            ['slug' => 'kill-creeping-shadow-10', 'title' => 'Pourchasseur d\'ombres', 'description' => 'Tuer 10 ombres rampantes', 'title_translations' => ['en' => 'Shadow Stalker'], 'description_translations' => ['en' => 'Kill 10 creeping shadows'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'creeping_shadow', 'count' => 10], 'reward' => ['gils' => 200]],
            ['slug' => 'kill-creeping-shadow-50', 'title' => 'Chasseur d\'ombres rampantes', 'description' => 'Tuer 50 ombres rampantes', 'title_translations' => ['en' => 'Creeping Shadow Hunter'], 'description_translations' => ['en' => 'Kill 50 creeping shadows'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'creeping_shadow', 'count' => 50], 'reward' => ['gils' => 500]],
            ['slug' => 'kill-creeping-shadow-100', 'title' => 'Exterminateur d\'ombres', 'description' => 'Tuer 100 ombres rampantes', 'title_translations' => ['en' => 'Shadow Exterminator'], 'description_translations' => ['en' => 'Kill 100 creeping shadows'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'creeping_shadow', 'count' => 100], 'reward' => ['gils' => 1000, 'title' => 'Exterminateur d\'ombres']],

            // Wyverne
            ['slug' => 'kill-wyvern-10', 'title' => 'Chasseur de wyvernes', 'description' => 'Tuer 10 wyvernes', 'title_translations' => ['en' => 'Wyvern Hunter'], 'description_translations' => ['en' => 'Kill 10 wyverns'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'wyvern', 'count' => 10], 'reward' => ['gils' => 300]],
            ['slug' => 'kill-wyvern-50', 'title' => 'Dompteur de wyvernes', 'description' => 'Tuer 50 wyvernes', 'title_translations' => ['en' => 'Wyvern Tamer'], 'description_translations' => ['en' => 'Kill 50 wyverns'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'wyvern', 'count' => 50], 'reward' => ['gils' => 800]],
            ['slug' => 'kill-wyvern-100', 'title' => 'Exterminateur de wyvernes', 'description' => 'Tuer 100 wyvernes', 'title_translations' => ['en' => 'Wyvern Exterminator'], 'description_translations' => ['en' => 'Kill 100 wyverns'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'wyvern', 'count' => 100], 'reward' => ['gils' => 1500, 'title' => 'Exterminateur de wyvernes']],
            // Chevalier maudit
            ['slug' => 'kill-cursed-knight-10', 'title' => 'Briseur de malédictions', 'description' => 'Tuer 10 chevaliers maudits', 'title_translations' => ['en' => 'Curse Breaker'], 'description_translations' => ['en' => 'Kill 10 cursed knights'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'cursed_knight', 'count' => 10], 'reward' => ['gils' => 350]],
            ['slug' => 'kill-cursed-knight-50', 'title' => 'Chasseur de chevaliers maudits', 'description' => 'Tuer 50 chevaliers maudits', 'title_translations' => ['en' => 'Cursed Knight Hunter'], 'description_translations' => ['en' => 'Kill 50 cursed knights'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'cursed_knight', 'count' => 50], 'reward' => ['gils' => 900]],
            ['slug' => 'kill-cursed-knight-100', 'title' => 'Exterminateur de chevaliers maudits', 'description' => 'Tuer 100 chevaliers maudits', 'title_translations' => ['en' => 'Cursed Knight Exterminator'], 'description_translations' => ['en' => 'Kill 100 cursed knights'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'cursed_knight', 'count' => 100], 'reward' => ['gils' => 1800, 'title' => 'Exterminateur de chevaliers maudits']],
            // Naga
            ['slug' => 'kill-naga-10', 'title' => 'Chasseur de nagas', 'description' => 'Tuer 10 nagas', 'title_translations' => ['en' => 'Naga Hunter'], 'description_translations' => ['en' => 'Kill 10 nagas'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'naga', 'count' => 10], 'reward' => ['gils' => 350]],
            ['slug' => 'kill-naga-50', 'title' => 'Dompteur de nagas', 'description' => 'Tuer 50 nagas', 'title_translations' => ['en' => 'Naga Tamer'], 'description_translations' => ['en' => 'Kill 50 nagas'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'naga', 'count' => 50], 'reward' => ['gils' => 900]],
            ['slug' => 'kill-naga-100', 'title' => 'Exterminateur de nagas', 'description' => 'Tuer 100 nagas', 'title_translations' => ['en' => 'Naga Exterminator'], 'description_translations' => ['en' => 'Kill 100 nagas'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'naga', 'count' => 100], 'reward' => ['gils' => 1800, 'title' => 'Exterminateur de nagas']],
            // Golem de cristal
            ['slug' => 'kill-crystal-golem-10', 'title' => 'Briseur de cristaux', 'description' => 'Tuer 10 golems de cristal', 'title_translations' => ['en' => 'Crystal Breaker'], 'description_translations' => ['en' => 'Kill 10 crystal golems'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'crystal_golem', 'count' => 10], 'reward' => ['gils' => 400]],
            ['slug' => 'kill-crystal-golem-50', 'title' => 'Chasseur de golems de cristal', 'description' => 'Tuer 50 golems de cristal', 'title_translations' => ['en' => 'Crystal Golem Hunter'], 'description_translations' => ['en' => 'Kill 50 crystal golems'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'crystal_golem', 'count' => 50], 'reward' => ['gils' => 1000]],
            ['slug' => 'kill-crystal-golem-100', 'title' => 'Exterminateur de golems de cristal', 'description' => 'Tuer 100 golems de cristal', 'title_translations' => ['en' => 'Crystal Golem Exterminator'], 'description_translations' => ['en' => 'Kill 100 crystal golems'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'crystal_golem', 'count' => 100], 'reward' => ['gils' => 2000, 'title' => 'Exterminateur de golems de cristal']],

            // Archidruide corrompu
            ['slug' => 'kill-corrupted-archdruid-10', 'title' => 'Purificateur de druides', 'description' => 'Tuer 10 archidruides corrompus', 'title_translations' => ['en' => 'Druid Purifier'], 'description_translations' => ['en' => 'Kill 10 corrupted archdruids'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'corrupted_archdruid', 'count' => 10], 'reward' => ['gils' => 400]],
            ['slug' => 'kill-corrupted-archdruid-50', 'title' => 'Chasseur d\'archidruides', 'description' => 'Tuer 50 archidruides corrompus', 'title_translations' => ['en' => 'Archdruid Hunter'], 'description_translations' => ['en' => 'Kill 50 corrupted archdruids'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'corrupted_archdruid', 'count' => 50], 'reward' => ['gils' => 1000]],
            ['slug' => 'kill-corrupted-archdruid-100', 'title' => 'Exterminateur d\'archidruides', 'description' => 'Tuer 100 archidruides corrompus', 'title_translations' => ['en' => 'Archdruid Exterminator'], 'description_translations' => ['en' => 'Kill 100 corrupted archdruids'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'corrupted_archdruid', 'count' => 100], 'reward' => ['gils' => 2000, 'title' => 'Exterminateur d\'archidruides']],
            // Liche mineure
            ['slug' => 'kill-lesser-lich-10', 'title' => 'Briseur de phylactères', 'description' => 'Tuer 10 liches mineures', 'title_translations' => ['en' => 'Phylactery Breaker'], 'description_translations' => ['en' => 'Kill 10 lesser liches'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'lesser_lich', 'count' => 10], 'reward' => ['gils' => 450]],
            ['slug' => 'kill-lesser-lich-50', 'title' => 'Chasseur de liches', 'description' => 'Tuer 50 liches mineures', 'title_translations' => ['en' => 'Lich Hunter'], 'description_translations' => ['en' => 'Kill 50 lesser liches'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'lesser_lich', 'count' => 50], 'reward' => ['gils' => 1200]],
            ['slug' => 'kill-lesser-lich-100', 'title' => 'Exterminateur de liches', 'description' => 'Tuer 100 liches mineures', 'title_translations' => ['en' => 'Lich Exterminator'], 'description_translations' => ['en' => 'Kill 100 lesser liches'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'lesser_lich', 'count' => 100], 'reward' => ['gils' => 2500, 'title' => 'Exterminateur de liches']],
            // Hydre des marais
            ['slug' => 'kill-swamp-hydra-10', 'title' => 'Trancheur de têtes', 'description' => 'Tuer 10 hydres des marais', 'title_translations' => ['en' => 'Head Splitter'], 'description_translations' => ['en' => 'Kill 10 swamp hydras'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'swamp_hydra', 'count' => 10], 'reward' => ['gils' => 500]],
            ['slug' => 'kill-swamp-hydra-50', 'title' => 'Chasseur d\'hydres', 'description' => 'Tuer 50 hydres des marais', 'title_translations' => ['en' => 'Hydra Hunter'], 'description_translations' => ['en' => 'Kill 50 swamp hydras'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'swamp_hydra', 'count' => 50], 'reward' => ['gils' => 1500]],
            ['slug' => 'kill-swamp-hydra-100', 'title' => 'Exterminateur d\'hydres', 'description' => 'Tuer 100 hydres des marais', 'title_translations' => ['en' => 'Hydra Exterminator'], 'description_translations' => ['en' => 'Kill 100 swamp hydras'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'swamp_hydra', 'count' => 100], 'reward' => ['gils' => 3000, 'title' => 'Exterminateur d\'hydres']],
            // Forgeron abyssal
            ['slug' => 'kill-abyssal-blacksmith-10', 'title' => 'Briseur de forges', 'description' => 'Tuer 10 forgerons abyssaux', 'title_translations' => ['en' => 'Forge Breaker'], 'description_translations' => ['en' => 'Kill 10 abyssal blacksmiths'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'abyssal_blacksmith', 'count' => 10], 'reward' => ['gils' => 600]],
            ['slug' => 'kill-abyssal-blacksmith-50', 'title' => 'Chasseur de forgerons', 'description' => 'Tuer 50 forgerons abyssaux', 'title_translations' => ['en' => 'Blacksmith Hunter'], 'description_translations' => ['en' => 'Kill 50 abyssal blacksmiths'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'abyssal_blacksmith', 'count' => 50], 'reward' => ['gils' => 1800]],
            ['slug' => 'kill-abyssal-blacksmith-100', 'title' => 'Exterminateur de forgerons', 'description' => 'Tuer 100 forgerons abyssaux', 'title_translations' => ['en' => 'Blacksmith Exterminator'], 'description_translations' => ['en' => 'Kill 100 abyssal blacksmiths'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'abyssal_blacksmith', 'count' => 100], 'reward' => ['gils' => 3500, 'title' => 'Exterminateur de forgerons']],

            // === BOSS DE ZONE (tâche 66) ===
            // Gardien de la Forêt
            ['slug' => 'kill-forest-guardian-1', 'title' => 'Gardien terrassé', 'description' => 'Vaincre le Gardien de la Forêt', 'title_translations' => ['en' => 'Guardian Felled'], 'description_translations' => ['en' => 'Defeat the Forest Guardian'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'forest_guardian', 'count' => 1], 'reward' => ['gils' => 1000, 'title' => 'Protecteur de la forêt']],
            // Seigneur de la Forge
            ['slug' => 'kill-forge-lord-1', 'title' => 'Seigneur de la forge vaincu', 'description' => 'Vaincre le Seigneur de la Forge', 'title_translations' => ['en' => 'Forge Lord Vanquished'], 'description_translations' => ['en' => 'Defeat the Forge Lord'], 'category' => 'combat', 'criteria' => ['type' => 'mob_kill', 'monster_slug' => 'forge_lord', 'count' => 1], 'reward' => ['gils' => 1500, 'title' => 'Maître de la forge']],

            // === EXPLORATION: Monstres différents découverts ===
            ['slug' => 'discover-5', 'title' => 'Explorateur novice', 'description' => 'Combattre 5 types de monstres différents', 'title_translations' => ['en' => 'Novice Explorer'], 'description_translations' => ['en' => 'Fight 5 different types of monsters'], 'category' => 'exploration', 'criteria' => ['type' => 'monster_discovery', 'count' => 5], 'reward' => ['gils' => 100]],
            ['slug' => 'discover-10', 'title' => 'Explorateur confirmé', 'description' => 'Combattre 10 types de monstres différents', 'title_translations' => ['en' => 'Confirmed Explorer'], 'description_translations' => ['en' => 'Fight 10 different types of monsters'], 'category' => 'exploration', 'criteria' => ['type' => 'monster_discovery', 'count' => 10], 'reward' => ['gils' => 300]],
            ['slug' => 'discover-20', 'title' => 'Explorateur expert', 'description' => 'Combattre 20 types de monstres différents', 'title_translations' => ['en' => 'Expert Explorer'], 'description_translations' => ['en' => 'Fight 20 different types of monsters'], 'category' => 'exploration', 'criteria' => ['type' => 'monster_discovery', 'count' => 20], 'reward' => ['gils' => 1000, 'title' => 'Explorateur expert']],

            // === QUETES ===
            ['slug' => 'quest-5', 'title' => 'Aventurier débutant', 'description' => 'Compléter 5 quêtes', 'title_translations' => ['en' => 'Beginner Adventurer'], 'description_translations' => ['en' => 'Complete 5 quests'], 'category' => 'quests', 'criteria' => ['type' => 'quest_complete', 'count' => 5], 'reward' => ['gils' => 100]],
            ['slug' => 'quest-10', 'title' => 'Aventurier confirmé', 'description' => 'Compléter 10 quêtes', 'title_translations' => ['en' => 'Confirmed Adventurer'], 'description_translations' => ['en' => 'Complete 10 quests'], 'category' => 'quests', 'criteria' => ['type' => 'quest_complete', 'count' => 10], 'reward' => ['gils' => 300]],
            ['slug' => 'quest-25', 'title' => 'Aventurier aguerri', 'description' => 'Compléter 25 quêtes', 'title_translations' => ['en' => 'Seasoned Adventurer'], 'description_translations' => ['en' => 'Complete 25 quests'], 'category' => 'quests', 'criteria' => ['type' => 'quest_complete', 'count' => 25], 'reward' => ['gils' => 800]],
            ['slug' => 'quest-50', 'title' => 'Héros légendaire', 'description' => 'Compléter 50 quêtes', 'title_translations' => ['en' => 'Legendary Hero'], 'description_translations' => ['en' => 'Complete 50 quests'], 'category' => 'quests', 'criteria' => ['type' => 'quest_complete', 'count' => 50], 'reward' => ['gils' => 2000, 'title' => 'Héros légendaire']],

            // === DONJONS (tache 84) ===
            ['slug' => 'dungeon-clear-1', 'title' => 'Premier donjon', 'description' => 'Terminer un donjon', 'title_translations' => ['en' => 'First Dungeon'], 'description_translations' => ['en' => 'Clear a dungeon'], 'category' => 'combat', 'criteria' => ['type' => 'dungeon_clear', 'count' => 1], 'reward' => ['gils' => 500]],
            ['slug' => 'dungeon-clear-5', 'title' => 'Explorateur de donjons', 'description' => 'Terminer 5 donjons', 'title_translations' => ['en' => 'Dungeon Explorer'], 'description_translations' => ['en' => 'Clear 5 dungeons'], 'category' => 'combat', 'criteria' => ['type' => 'dungeon_clear', 'count' => 5], 'reward' => ['gils' => 1500]],
            ['slug' => 'dungeon-clear-10', 'title' => 'Maître des profondeurs', 'description' => 'Terminer 10 donjons', 'title_translations' => ['en' => 'Master of the Depths'], 'description_translations' => ['en' => 'Clear 10 dungeons'], 'category' => 'combat', 'criteria' => ['type' => 'dungeon_clear', 'count' => 10], 'reward' => ['gils' => 3000, 'title' => 'Maître des profondeurs']],
            ['slug' => 'dungeon-clear-mythic-1', 'title' => 'Défi mythique', 'description' => 'Terminer un donjon en difficulté Mythique', 'title_translations' => ['en' => 'Mythic Challenge'], 'description_translations' => ['en' => 'Clear a dungeon on Mythic difficulty'], 'category' => 'combat', 'criteria' => ['type' => 'dungeon_clear_mythic', 'count' => 1], 'reward' => ['gils' => 2000, 'title' => 'Conquérant mythique']],

            // === RECOLTE ===
            ['slug' => 'gather-10', 'title' => 'Cueilleur du dimanche', 'description' => 'Récolter 10 ressources', 'title_translations' => ['en' => 'Sunday Gatherer'], 'description_translations' => ['en' => 'Gather 10 resources'], 'category' => 'gathering', 'criteria' => ['type' => 'gathering', 'count' => 10], 'reward' => ['gils' => 50]],
            ['slug' => 'gather-50', 'title' => 'Récolteur assidu', 'description' => 'Récolter 50 ressources', 'title_translations' => ['en' => 'Diligent Gatherer'], 'description_translations' => ['en' => 'Gather 50 resources'], 'category' => 'gathering', 'criteria' => ['type' => 'gathering', 'count' => 50], 'reward' => ['gils' => 200]],
            ['slug' => 'gather-200', 'title' => 'Maître récolteur', 'description' => 'Récolter 200 ressources', 'title_translations' => ['en' => 'Master Gatherer'], 'description_translations' => ['en' => 'Gather 200 resources'], 'category' => 'gathering', 'criteria' => ['type' => 'gathering', 'count' => 200], 'reward' => ['gils' => 800, 'title' => 'Maître récolteur']],
            ['slug' => 'gather-500', 'title' => 'Pilleur de la nature', 'description' => 'Récolter 500 ressources', 'title_translations' => ['en' => 'Nature Plunderer'], 'description_translations' => ['en' => 'Gather 500 resources'], 'category' => 'gathering', 'criteria' => ['type' => 'gathering', 'count' => 500], 'reward' => ['gils' => 2000, 'title' => 'Pilleur de la nature']],

            // === CRAFT ===
            ['slug' => 'craft-5', 'title' => 'Apprenti artisan', 'description' => 'Fabriquer 5 objets', 'title_translations' => ['en' => 'Apprentice Artisan'], 'description_translations' => ['en' => 'Craft 5 items'], 'category' => 'craft', 'criteria' => ['type' => 'craft', 'count' => 5], 'reward' => ['gils' => 50]],
            ['slug' => 'craft-25', 'title' => 'Artisan confirmé', 'description' => 'Fabriquer 25 objets', 'title_translations' => ['en' => 'Confirmed Artisan'], 'description_translations' => ['en' => 'Craft 25 items'], 'category' => 'craft', 'criteria' => ['type' => 'craft', 'count' => 25], 'reward' => ['gils' => 300]],
            ['slug' => 'craft-100', 'title' => 'Maître artisan', 'description' => 'Fabriquer 100 objets', 'title_translations' => ['en' => 'Master Artisan'], 'description_translations' => ['en' => 'Craft 100 items'], 'category' => 'craft', 'criteria' => ['type' => 'craft', 'count' => 100], 'reward' => ['gils' => 1000, 'title' => 'Maître artisan']],
            ['slug' => 'craft-250', 'title' => 'Légende de la forge', 'description' => 'Fabriquer 250 objets', 'title_translations' => ['en' => 'Forge Legend'], 'description_translations' => ['en' => 'Craft 250 items'], 'category' => 'craft', 'criteria' => ['type' => 'craft', 'count' => 250], 'reward' => ['gils' => 3000, 'title' => 'Légende de la forge']],

            // === TRAME NARRATIVE ===
            ['slug' => 'acte3-convergence', 'title' => 'La Convergence', 'description' => 'Terminer la trame de l\'Acte 3 — vaincre le Gardien de la Convergence et decouvrir la verite du cristal d\'Amethyste', 'title_translations' => ['en' => 'The Convergence'], 'description_translations' => ['en' => 'Complete the Act 3 storyline — defeat the Guardian of the Convergence and uncover the truth of the Amethyst crystal'], 'category' => 'quests', 'criteria' => ['type' => 'quest_complete', 'quest_slug' => 'quest_acte3_epilogue', 'count' => 1], 'reward' => ['gils' => 10000, 'title' => 'Heros de la Convergence']],

            // === SECRETS (hidden achievements) ===
            ['slug' => 'secret-first-death', 'title' => 'Première chute', 'description' => 'Mourir pour la première fois', 'title_translations' => ['en' => 'First Fall'], 'description_translations' => ['en' => 'Die for the first time'], 'category' => 'secrets', 'criteria' => ['type' => 'player_death', 'count' => 1], 'reward' => ['gils' => 25], 'hidden' => true],
            ['slug' => 'secret-death-10', 'title' => 'Habitué de l\'au-delà', 'description' => 'Mourir 10 fois', 'title_translations' => ['en' => 'Regular of the Afterlife'], 'description_translations' => ['en' => 'Die 10 times'], 'category' => 'secrets', 'criteria' => ['type' => 'player_death', 'count' => 10], 'reward' => ['gils' => 100], 'hidden' => true],
            ['slug' => 'secret-flee-1', 'title' => 'La fuite est un art', 'description' => 'Fuir un combat', 'title_translations' => ['en' => 'Fleeing is an Art'], 'description_translations' => ['en' => 'Flee a battle'], 'category' => 'secrets', 'criteria' => ['type' => 'combat_flee', 'count' => 1], 'reward' => ['gils' => 50], 'hidden' => true],
            ['slug' => 'secret-flee-10', 'title' => 'Couard professionnel', 'description' => 'Fuir 10 combats', 'title_translations' => ['en' => 'Professional Coward'], 'description_translations' => ['en' => 'Flee 10 battles'], 'category' => 'secrets', 'criteria' => ['type' => 'combat_flee', 'count' => 10], 'reward' => ['gils' => 200, 'title' => 'Couard professionnel'], 'hidden' => true],
            ['slug' => 'secret-gather-1000', 'title' => 'L\'infatigable', 'description' => 'Récolter 1000 ressources', 'title_translations' => ['en' => 'The Tireless'], 'description_translations' => ['en' => 'Gather 1000 resources'], 'category' => 'secrets', 'criteria' => ['type' => 'gathering', 'count' => 1000], 'reward' => ['gils' => 5000, 'title' => 'L\'infatigable'], 'hidden' => true],
            ['slug' => 'secret-craft-500', 'title' => 'Forgeron des dieux', 'description' => 'Fabriquer 500 objets', 'title_translations' => ['en' => 'Forger of the Gods'], 'description_translations' => ['en' => 'Craft 500 items'], 'category' => 'secrets', 'criteria' => ['type' => 'craft', 'count' => 500], 'reward' => ['gils' => 5000, 'title' => 'Forgeron des dieux'], 'hidden' => true],
            ['slug' => 'secret-quest-100', 'title' => 'L\'éternel aventurier', 'description' => 'Compléter 100 quêtes', 'title_translations' => ['en' => 'The Eternal Adventurer'], 'description_translations' => ['en' => 'Complete 100 quests'], 'category' => 'secrets', 'criteria' => ['type' => 'quest_complete', 'count' => 100], 'reward' => ['gils' => 5000, 'title' => 'L\'éternel aventurier'], 'hidden' => true],

            // === TUTORIEL ===
            ['slug' => 'tutorial-complete', 'title' => 'Premiers pas', 'description' => 'Terminer le tutoriel d\'introduction.', 'title_translations' => ['en' => 'First Steps'], 'description_translations' => ['en' => 'Complete the introduction tutorial.'], 'category' => 'exploration', 'criteria' => ['type' => 'tutorial_complete', 'count' => 1], 'reward' => ['gils' => 100]],
        ];

        foreach ($achievements as $data) {
            $achievement = new Achievement();
            $achievement->setSlug($data['slug']);
            $achievement->setTitle($data['title']);
            if (isset($data['title_translations']) && \is_array($data['title_translations'])) {
                $achievement->setTitleTranslations($data['title_translations']);
            }
            $achievement->setDescription($data['description']);
            if (isset($data['description_translations']) && \is_array($data['description_translations'])) {
                $achievement->setDescriptionTranslations($data['description_translations']);
            }
            $achievement->setCategory($data['category']);
            $achievement->setCriteria($data['criteria']);
            $achievement->setReward($data['reward']);
            $achievement->setHidden($data['hidden'] ?? false);
            $achievement->setCreatedAt(new \DateTime());
            $achievement->setUpdatedAt(new \DateTime());

            $manager->persist($achievement);
            $this->addReference('achievement_' . $data['slug'], $achievement);
        }

        $manager->flush();
    }
}
