<?php

namespace App\DataFixtures;

use App\Entity\Game\Spell;
use App\Enum\Element;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;

class SpellFixtures extends Fixture
{
    public function load(ObjectManager $manager): void
    {
        $spellsData = $this->getSpellsData();

        // Création des sorts pour chaque élément
        foreach ($spellsData as $key => $data) {
            $spell = new Spell();
            $spell->setSlug($data['slug']);
            $spell->setDamage($data['damage']);
            $spell->setElement($data['element']);
            $spell->setHeal($data['heal']);
            $spell->setName($data['name']);
            $spell->setDescription($data['description']);
            $spell->setHit($data['hit'] ?? 90);
            $spell->setCritical($data['critical'] ?? 5);
            $spell->setEnergyCost($data['energyCost'] ?? 0);
            $spell->setCooldown($data['cooldown'] ?? null);
            $spell->setStatusEffectSlug($data['statusEffectSlug'] ?? null);
            $spell->setAoeTargets($data['aoeTargets'] ?? 1);
            $spell->setLevel($data['level'] ?? 1);
            $spell->setValueType($data['valueType'] ?? 'fixed');
            $spell->setCreatedAt(new \DateTime());
            $spell->setUpdatedAt(new \DateTime());

            $manager->persist($spell);
            $this->addReference($key, $spell);
        }

        $manager->flush();
    }

    /**
     * Retourne les données des sorts.
     */
    private function getSpellsData(): array
    {
        return [
            // Sorts de feu
            'fire_ball' => [
                'slug' => 'fire-ball',
                'damage' => 2,
                'element' => Element::Fire,
                'heal' => null,
                'name' => 'Boule de feu',
                'description' => 'Une boule de feu pour tout cramer',
                'hit' => 90,
                'energyCost' => 5,
                'statusEffectSlug' => 'burn',
                'critical' => 8,
                'level' => 1,
            ],
            'flame' => [
                'slug' => 'flame',
                'damage' => 1,
                'element' => Element::Fire,
                'heal' => null,
                'name' => 'Flammèche',
                'description' => 'Un sort de flammèche',
                'hit' => 90,
                'level' => 1,
            ],
            'flamer' => [
                'slug' => 'flamer',
                'damage' => 3,
                'element' => Element::Fire,
                'heal' => null,
                'name' => 'Feu',
                'description' => 'Un sort de feu',
                'hit' => 90,
                'level' => 2,
            ],
            'flame_rain' => [
                'slug' => 'flame-rain',
                'damage' => 5,
                'element' => Element::Fire,
                'heal' => null,
                'name' => 'Pluie de flammes',
                'description' => 'Une pluie de flammes qui carbonise tout sur une large zone',
                'hit' => 85,
                'energyCost' => 12,
                'cooldown' => 2,
                'statusEffectSlug' => 'burn',
                'critical' => 10,
                'aoeTargets' => 0,
                'level' => 3,
            ],
            'inferno' => [
                'slug' => 'inferno',
                'damage' => 7,
                'element' => Element::Fire,
                'heal' => null,
                'name' => 'Inferno',
                'description' => 'Un brasier dévastateur qui consume tout sur son passage',
                'hit' => 85,
                'energyCost' => 20,
                'cooldown' => 3,
                'statusEffectSlug' => 'burn',
                'critical' => 12,
                'aoeTargets' => 0,
                'level' => 4,
            ],
            'fire_wall' => [
                'slug' => 'fire-wall',
                'damage' => 4,
                'element' => Element::Fire,
                'heal' => null,
                'name' => 'Mur de feu',
                'description' => 'Crée un mur de flammes infranchissable',
                'hit' => 95,
                'level' => 2,
            ],
            'fire_nova' => [
                'slug' => 'fire-nova',
                'damage' => 6,
                'element' => Element::Fire,
                'heal' => null,
                'name' => 'Nova de feu',
                'description' => 'Une explosion de feu qui se propage dans toutes les directions',
                'hit' => 85,
                'level' => 3,
            ],
            'phoenix_flame' => [
                'slug' => 'phoenix-flame',
                'damage' => 5,
                'element' => Element::Fire,
                'heal' => 2,
                'name' => 'Flamme du phénix',
                'description' => 'Des flammes régénératrices qui brûlent et soignent à la fois',
                'hit' => 90,
                'level' => 3,
            ],
            'meteor_strike' => [
                'slug' => 'meteor-strike',
                'damage' => 8,
                'element' => Element::Fire,
                'heal' => null,
                'name' => 'Frappe météorique',
                'description' => 'Invoque un météore enflammé qui s\'écrase sur l\'ennemi',
                'hit' => 75,
                'level' => 4,
            ],
            'burning_touch' => [
                'slug' => 'burning-touch',
                'damage' => 2,
                'element' => Element::Fire,
                'heal' => null,
                'name' => 'Toucher brûlant',
                'description' => 'Un simple contact qui inflige des brûlures',
                'hit' => 100,
                'level' => 1,
            ],
            'heat_wave' => [
                'slug' => 'heat-wave',
                'damage' => 3,
                'element' => Element::Fire,
                'heal' => null,
                'name' => 'Vague de chaleur',
                'description' => 'Une onde de chaleur qui affaiblit les ennemis',
                'hit' => 95,
                'level' => 2,
            ],
            'dragon_breath' => [
                'slug' => 'dragon-breath',
                'damage' => 6,
                'element' => Element::Fire,
                'heal' => null,
                'name' => 'Souffle du dragon',
                'description' => 'Un souffle de feu devastateur',
                'hit' => 85,
                'statusEffectSlug' => 'burn',
                'aoeTargets' => 0,
                'critical' => 10,
                'level' => 4,
            ],
            'volcanic_eruption' => [
                'slug' => 'volcanic-eruption',
                'damage' => 10,
                'element' => Element::Fire,
                'heal' => null,
                'name' => 'Eruption volcanique',
                'description' => 'Dechaine la puissance d\'un volcan sur les ennemis',
                'hit' => 70,
                'energyCost' => 30,
                'cooldown' => 5,
                'statusEffectSlug' => 'burn',
                'critical' => 15,
                'aoeTargets' => 0,
                'level' => 5,
            ],
            'ember_shield' => [
                'slug' => 'ember-shield',
                'damage' => 1,
                'element' => Element::Fire,
                'heal' => 3,
                'name' => 'Bouclier d\'étincelles',
                'description' => 'Un bouclier de braises qui protège et brûle les attaquants',
                'hit' => 100,
                'level' => 2,
            ],
            'fire_whip' => [
                'slug' => 'fire-whip',
                'damage' => 4,
                'element' => Element::Fire,
                'heal' => null,
                'name' => 'Fouet de feu',
                'description' => 'Un fouet enflammé qui frappe à distance',
                'hit' => 90,
                'level' => 2,
            ],
            'combustion' => [
                'slug' => 'combustion',
                'damage' => 3,
                'element' => Element::Fire,
                'heal' => null,
                'name' => 'Combustion',
                'description' => 'Enflamme instantanément la cible',
                'hit' => 95,
                'level' => 2,
            ],

            // Sorts de vie
            'life_heal' => [
                'slug' => 'life-heal',
                'damage' => null,
                'element' => Element::Light,
                'heal' => 5,
                'name' => 'Soin mineur',
                'description' => 'Un soin mineur qui fait du bien',
                'hit' => 100,
                'energyCost' => 5,
                'level' => 1,
            ],
            'rejuvenation' => [
                'slug' => 'rejuvenation',
                'damage' => null,
                'element' => Element::Light,
                'heal' => 8,
                'name' => 'Regeneration',
                'description' => 'Un sort de regeneration qui restaure progressivement la sante',
                'hit' => 100,
                'energyCost' => 10,
                'statusEffectSlug' => 'regeneration',
                'level' => 2,
            ],
            'divine_blessing' => [
                'slug' => 'divine-blessing',
                'damage' => null,
                'element' => Element::Light,
                'heal' => 12,
                'name' => 'Benediction divine',
                'description' => 'Une puissante benediction qui soigne les blessures graves',
                'hit' => 100,
                'energyCost' => 18,
                'cooldown' => 3,
                'statusEffectSlug' => 'regeneration-strong',
                'level' => 4,
            ],
            'healing_wave' => [
                'slug' => 'healing-wave',
                'damage' => null,
                'element' => Element::Light,
                'heal' => 7,
                'name' => 'Vague de guérison',
                'description' => 'Une vague d\'énergie curative qui soigne les blessures',
                'hit' => 100,
                'level' => 2,
            ],
            'life_transfer' => [
                'slug' => 'life-transfer',
                'damage' => 2,
                'element' => Element::Light,
                'heal' => 4,
                'name' => 'Transfert de vie',
                'description' => 'Transfère l\'énergie vitale de l\'ennemi vers soi',
                'hit' => 90,
                'level' => 2,
            ],
            'holy_light' => [
                'slug' => 'holy-light',
                'damage' => 3,
                'element' => Element::Light,
                'heal' => 3,
                'name' => 'Lumiere',
                'description' => 'Une lumiere divine qui soigne les allies et blesse les ennemis',
                'hit' => 95,
                'energyCost' => 6,
                'level' => 2,
            ],
            'vitality_surge' => [
                'slug' => 'vitality-surge',
                'damage' => null,
                'element' => Element::Light,
                'heal' => 10,
                'name' => 'Afflux de vitalité',
                'description' => 'Un puissant afflux d\'énergie vitale qui restaure la santé',
                'hit' => 100,
                'level' => 3,
            ],
            'life_shield' => [
                'slug' => 'life-shield',
                'damage' => null,
                'element' => Element::Light,
                'heal' => 6,
                'name' => 'Bouclier de vie',
                'description' => 'Crée un bouclier protecteur qui absorbe les dégâts',
                'hit' => 100,
                'level' => 2,
            ],
            'angelic_touch' => [
                'slug' => 'angelic-touch',
                'damage' => null,
                'element' => Element::Light,
                'heal' => 4,
                'name' => 'Toucher angélique',
                'description' => 'Un toucher qui apaise les blessures',
                'hit' => 100,
                'level' => 1,
            ],
            'purification' => [
                'slug' => 'purification',
                'damage' => 1,
                'element' => Element::Light,
                'heal' => 5,
                'name' => 'Purification',
                'description' => 'Purifie le corps et l\'esprit, eliminant les afflictions',
                'hit' => 100,
                'energyCost' => 10,
                'level' => 3,
            ],
            'celestial_blessing' => [
                'slug' => 'celestial-blessing',
                'damage' => null,
                'element' => Element::Light,
                'heal' => 15,
                'name' => 'Bénédiction céleste',
                'description' => 'Une bénédiction des cieux qui restaure une grande quantité de santé',
                'hit' => 95,
                'level' => 5,
            ],
            'life_burst' => [
                'slug' => 'life-burst',
                'damage' => null,
                'element' => Element::Light,
                'heal' => 9,
                'name' => 'Explosion de vie',
                'description' => 'Une explosion d\'énergie vitale qui soigne instantanément',
                'hit' => 100,
                'level' => 3,
            ],
            'divine_intervention' => [
                'slug' => 'divine-intervention',
                'damage' => 5,
                'element' => Element::Light,
                'heal' => 5,
                'name' => 'Jugement sacre',
                'description' => 'Un jugement divin qui soigne les allies et punit les ennemis',
                'hit' => 90,
                'energyCost' => 22,
                'cooldown' => 4,
                'critical' => 15,
                'level' => 5,
            ],
            'healing_touch' => [
                'slug' => 'healing-touch',
                'damage' => null,
                'element' => Element::Light,
                'heal' => 3,
                'name' => 'Toucher guérisseur',
                'description' => 'Un simple toucher qui soigne les blessures légères',
                'hit' => 100,
                'level' => 1,
            ],
            'life_bloom' => [
                'slug' => 'life-bloom',
                'damage' => null,
                'element' => Element::Light,
                'heal' => 6,
                'name' => 'Floraison de vie',
                'description' => 'Une énergie vitale qui se répand progressivement',
                'hit' => 100,
                'level' => 2,
            ],
            'sacred_light' => [
                'slug' => 'sacred-light',
                'damage' => 4,
                'element' => Element::Light,
                'heal' => 2,
                'name' => 'Lumière sacrée',
                'description' => 'Un rayon de lumière divine qui purifie et soigne',
                'hit' => 95,
                'level' => 2,
            ],

            // Sorts de mort
            'punishment' => [
                'slug' => 'punishment',
                'damage' => 1,
                'element' => Element::Dark,
                'heal' => null,
                'name' => 'Châtiment',
                'description' => 'Un sort de châtiment',
                'hit' => 90,
                'level' => 1,
            ],
            'soul_drain' => [
                'slug' => 'soul-drain',
                'damage' => 3,
                'element' => Element::Dark,
                'heal' => 1,
                'name' => 'Drain de vie',
                'description' => 'Aspire l\'energie vitale de la cible pour se soigner',
                'hit' => 85,
                'energyCost' => 6,
                'level' => 2,
            ],
            'death_touch' => [
                'slug' => 'death-touch',
                'damage' => 4,
                'element' => Element::Dark,
                'heal' => null,
                'name' => 'Toucher mortel',
                'description' => 'Un contact qui inflige une douleur intense',
                'hit' => 80,
                'level' => 2,
            ],
            'shadow_bolt' => [
                'slug' => 'shadow-bolt',
                'damage' => 5,
                'element' => Element::Dark,
                'heal' => null,
                'name' => 'Éclair d\'ombre',
                'description' => 'Un projectile d\'énergie sombre qui frappe la cible',
                'hit' => 85,
                'level' => 3,
            ],
            'life_leech' => [
                'slug' => 'life-leech',
                'damage' => 4,
                'element' => Element::Dark,
                'heal' => 2,
                'name' => 'Sangsue vitale',
                'description' => 'Absorbe l\'énergie vitale de la cible',
                'hit' => 90,
                'level' => 2,
            ],
            'death_grip' => [
                'slug' => 'death-grip',
                'damage' => 3,
                'element' => Element::Dark,
                'heal' => null,
                'name' => 'Emprise de la mort',
                'description' => 'Une main spectrale qui saisit et blesse la cible',
                'hit' => 95,
                'level' => 2,
            ],
            'shadow_wave' => [
                'slug' => 'shadow-wave',
                'damage' => 6,
                'element' => Element::Dark,
                'heal' => null,
                'name' => 'Vague d\'ombre',
                'description' => 'Une vague d\'énergie sombre qui balaye la zone',
                'hit' => 80,
                'level' => 3,
            ],
            'necrotic_touch' => [
                'slug' => 'necrotic-touch',
                'damage' => 2,
                'element' => Element::Dark,
                'heal' => null,
                'name' => 'Toucher nécrotique',
                'description' => 'Un toucher qui provoque la nécrose des tissus',
                'hit' => 100,
                'level' => 1,
            ],
            'dark_harvest' => [
                'slug' => 'dark-harvest',
                'damage' => 7,
                'element' => Element::Dark,
                'heal' => 3,
                'name' => 'Moisson sombre',
                'description' => 'Recolte l\'energie vitale des ennemis affaiblis',
                'hit' => 75,
                'energyCost' => 18,
                'cooldown' => 3,
                'statusEffectSlug' => 'poison-strong',
                'critical' => 12,
                'level' => 4,
            ],
            'soul_rip' => [
                'slug' => 'soul-rip',
                'damage' => 8,
                'element' => Element::Dark,
                'heal' => null,
                'name' => 'Déchirure d\'âme',
                'description' => 'Déchire l\'âme de la cible, causant une douleur intense',
                'hit' => 70,
                'level' => 4,
            ],
            'death_nova' => [
                'slug' => 'death-nova',
                'damage' => 6,
                'element' => Element::Dark,
                'heal' => null,
                'name' => 'Nova de mort',
                'description' => 'Une explosion d\'énergie mortelle qui se propage',
                'hit' => 80,
                'level' => 3,
            ],
            'shadow_mend' => [
                'slug' => 'shadow-mend',
                'damage' => 1,
                'element' => Element::Dark,
                'heal' => 5,
                'name' => 'Guérison des ombres',
                'description' => 'Utilise l\'énergie sombre pour soigner les blessures',
                'hit' => 95,
                'level' => 2,
            ],
            'plague_strike' => [
                'slug' => 'plague-strike',
                'damage' => 3,
                'element' => Element::Dark,
                'heal' => null,
                'name' => 'Malediction',
                'description' => 'Maudit la cible, empoisonnant son corps et son ame',
                'hit' => 90,
                'energyCost' => 10,
                'statusEffectSlug' => 'poison',
                'level' => 3,
            ],
            'death_coil' => [
                'slug' => 'death-coil',
                'damage' => 5,
                'element' => Element::Dark,
                'heal' => null,
                'name' => 'Spirale de mort',
                'description' => 'Une spirale d\'énergie nécrotique qui frappe la cible',
                'hit' => 85,
                'level' => 3,
            ],
            'soul_siphon' => [
                'slug' => 'soul-siphon',
                'damage' => 4,
                'element' => Element::Dark,
                'heal' => 4,
                'name' => 'Siphon d\'âme',
                'description' => 'Siphonne l\'essence vitale de la cible',
                'hit' => 85,
                'level' => 3,
            ],
            'dark_ritual' => [
                'slug' => 'dark-ritual',
                'damage' => 2,
                'element' => Element::Dark,
                'heal' => 6,
                'name' => 'Rituel sombre',
                'description' => 'Un rituel qui sacrifie une partie de sa force pour se soigner',
                'hit' => 100,
                'level' => 3,
            ],

            // Sorts de terre
            'stone_throw' => [
                'slug' => 'stone-throw',
                'damage' => 1,
                'element' => Element::Earth,
                'heal' => null,
                'name' => 'Jet de cailloux',
                'description' => 'Un sort de jet de cailloux',
                'hit' => 90,
                'level' => 1,
            ],
            'earthquake' => [
                'slug' => 'earthquake',
                'damage' => 4,
                'element' => Element::Earth,
                'heal' => null,
                'name' => 'Tremblement de terre',
                'description' => 'Provoque un séisme qui déstabilise les ennemis',
                'hit' => 85,
                'level' => 2,
            ],
            'rock_armor' => [
                'slug' => 'rock-armor',
                'damage' => 0,
                'element' => Element::Earth,
                'heal' => 3,
                'name' => 'Parade',
                'description' => 'Une parade rocheuse qui absorbe les degats',
                'hit' => 100,
                'energyCost' => 5,
                'statusEffectSlug' => 'shield',
                'level' => 1,
            ],
            'boulder_throw' => [
                'slug' => 'boulder-throw',
                'damage' => 6,
                'element' => Element::Earth,
                'heal' => null,
                'name' => 'Lancer de rocher',
                'description' => 'Lance un énorme rocher sur l\'ennemi',
                'hit' => 80,
                'level' => 3,
            ],
            'earth_spike' => [
                'slug' => 'earth-spike',
                'damage' => 3,
                'element' => Element::Earth,
                'heal' => null,
                'name' => 'Pic de terre',
                'description' => 'Un pic rocheux jaillit du sol et transperce l\'ennemi',
                'hit' => 90,
                'level' => 2,
            ],
            'stone_spikes' => [
                'slug' => 'stone-spikes',
                'damage' => 4,
                'element' => Element::Earth,
                'heal' => null,
                'name' => 'Pics de pierre',
                'description' => 'Fait jaillir plusieurs pics de pierre acérés du sol',
                'hit' => 88,
                'level' => 2,
            ],
            'landslide' => [
                'slug' => 'landslide',
                'damage' => 5,
                'element' => Element::Earth,
                'heal' => null,
                'name' => 'Glissement de terrain',
                'description' => 'Déclenche un glissement de terrain qui ensevelit les ennemis',
                'hit' => 85,
                'level' => 3,
            ],
            'stone_skin' => [
                'slug' => 'stone-skin',
                'damage' => 0,
                'element' => Element::Earth,
                'heal' => 5,
                'name' => 'Bouclier magique',
                'description' => 'Un bouclier de pierre magique offrant une protection accrue',
                'hit' => 100,
                'energyCost' => 10,
                'statusEffectSlug' => 'shield-strong',
                'level' => 3,
            ],
            'earth_shield' => [
                'slug' => 'earth-shield',
                'damage' => 1,
                'element' => Element::Earth,
                'heal' => 4,
                'name' => 'Bouclier terreux',
                'description' => 'Un bouclier de terre qui protège et contre-attaque',
                'hit' => 100,
                'level' => 2,
            ],
            'crystal_spear' => [
                'slug' => 'crystal-spear',
                'damage' => 7,
                'element' => Element::Earth,
                'heal' => null,
                'name' => 'Lance de cristal',
                'description' => 'Une lance de cristal tranchante qui transperce les armures',
                'hit' => 85,
                'level' => 4,
            ],
            'quicksand' => [
                'slug' => 'quicksand',
                'damage' => 2,
                'element' => Element::Earth,
                'heal' => null,
                'name' => 'Sables mouvants',
                'description' => 'Transforme le sol en sables mouvants qui engloutissent l\'ennemi',
                'hit' => 95,
                'level' => 1,
            ],
            'stone_wall' => [
                'slug' => 'stone-wall',
                'damage' => 0,
                'element' => Element::Earth,
                'heal' => 6,
                'name' => 'Mur de fer',
                'description' => 'Erige un mur de fer infranchissable',
                'hit' => 100,
                'energyCost' => 20,
                'cooldown' => 4,
                'statusEffectSlug' => 'shield-strong',
                'level' => 4,
            ],
            'earth_blessing' => [
                'slug' => 'earth-blessing',
                'damage' => 0,
                'element' => Element::Earth,
                'heal' => 8,
                'name' => 'Bénédiction de la terre',
                'description' => 'Invoque la bénédiction de la terre pour soigner et protéger',
                'hit' => 100,
                'level' => 3,
            ],
            'mountain_strength' => [
                'slug' => 'mountain-strength',
                'damage' => 3,
                'element' => Element::Earth,
                'heal' => 3,
                'name' => 'Force de la montagne',
                'description' => 'Puise dans la force des montagnes pour renforcer le corps',
                'hit' => 95,
                'level' => 2,
            ],
            'crystal_growth' => [
                'slug' => 'crystal-growth',
                'damage' => 4,
                'element' => Element::Earth,
                'heal' => null,
                'name' => 'Croissance cristalline',
                'description' => 'Des cristaux acérés poussent rapidement et blessent l\'ennemi',
                'hit' => 90,
                'level' => 2,
            ],
            'tectonic_shift' => [
                'slug' => 'tectonic-shift',
                'damage' => 8,
                'element' => Element::Earth,
                'heal' => null,
                'name' => 'Déplacement tectonique',
                'description' => 'Provoque un violent déplacement des plaques tectoniques',
                'hit' => 75,
                'level' => 5,
            ],
            'petrification' => [
                'slug' => 'petrification',
                'damage' => 5,
                'element' => Element::Earth,
                'heal' => null,
                'name' => 'Pétrification',
                'description' => 'Transforme partiellement l\'ennemi en pierre',
                'hit' => 80,
                'level' => 3,
            ],

            // Sorts de métal
            'sword_10' => [
                'slug' => 'slug-10',
                'damage' => 1,
                'element' => Element::Metal,
                'heal' => null,
                'name' => "Coup d'épée",
                'description' => "Un coup d'épée neutre",
                'hit' => 90,
                'level' => 1,
            ],
            'sharp_blade' => [
                'slug' => 'sharp-blade',
                'damage' => 1,
                'element' => Element::Metal,
                'heal' => null,
                'name' => 'Frappe puissante',
                'description' => 'Une frappe puissante avec une lame tranchante',
                'hit' => 95,
                'energyCost' => 4,
                'critical' => 10,
                'level' => 1,
            ],
            'metal_storm' => [
                'slug' => 'metal-storm',
                'damage' => 5,
                'element' => Element::Metal,
                'heal' => null,
                'name' => 'Tempête métallique',
                'description' => 'Une pluie de fragments métalliques acérés',
                'hit' => 80,
                'level' => 3,
            ],
            'iron_fist' => [
                'slug' => 'iron-fist',
                'damage' => 3,
                'element' => Element::Metal,
                'heal' => null,
                'name' => 'Charge',
                'description' => 'Une charge brutale avec un poing de fer',
                'hit' => 90,
                'energyCost' => 8,
                'critical' => 12,
                'level' => 2,
            ],
            'blade_dance' => [
                'slug' => 'blade-dance',
                'damage' => 6,
                'element' => Element::Metal,
                'heal' => null,
                'name' => 'Tourbillon d\'epee',
                'description' => 'Un tourbillon devastateur de lames qui frappe tous les ennemis',
                'hit' => 85,
                'energyCost' => 15,
                'cooldown' => 2,
                'critical' => 15,
                'aoeTargets' => 0,
                'level' => 4,
            ],
            'steel_shield' => [
                'slug' => 'steel-shield',
                'damage' => 0,
                'element' => Element::Metal,
                'heal' => 4,
                'name' => 'Bouclier d\'acier',
                'description' => 'Un bouclier métallique qui offre une protection solide',
                'hit' => 100,
                'level' => 2,
            ],
            'razor_edge' => [
                'slug' => 'razor-edge',
                'damage' => 7,
                'element' => Element::Metal,
                'heal' => null,
                'name' => 'Lame rasoir',
                'description' => 'Une lame si fine qu\'elle coupe presque tout',
                'hit' => 80,
                'level' => 4,
            ],
            'metal_skin' => [
                'slug' => 'metal-skin',
                'damage' => 1,
                'element' => Element::Metal,
                'heal' => 5,
                'name' => 'Peau métallique',
                'description' => 'Transforme la peau en métal pour une protection accrue',
                'hit' => 100,
                'level' => 3,
            ],
            'shrapnel_burst' => [
                'slug' => 'shrapnel-burst',
                'damage' => 4,
                'element' => Element::Metal,
                'heal' => null,
                'name' => 'Explosion d\'éclats',
                'description' => 'Une explosion qui projette des éclats métalliques dans toutes les directions',
                'hit' => 85,
                'level' => 2,
            ],
            'iron_maiden' => [
                'slug' => 'iron-maiden',
                'damage' => 8,
                'element' => Element::Metal,
                'heal' => null,
                'name' => 'Vierge de fer',
                'description' => 'Emprisonne l\'ennemi dans une cage de pointes métalliques',
                'hit' => 75,
                'level' => 5,
            ],
            'chain_lightning' => [
                'slug' => 'chain-lightning',
                'damage' => 5,
                'element' => Element::Metal,
                'heal' => null,
                'name' => 'Chaîne d\'éclairs',
                'description' => 'Des chaînes métalliques chargées d\'électricité frappent l\'ennemi',
                'hit' => 85,
                'level' => 3,
            ],
            'metallic_regeneration' => [
                'slug' => 'metallic-regeneration',
                'damage' => 0,
                'element' => Element::Metal,
                'heal' => 6,
                'name' => 'Régénération métallique',
                'description' => 'Utilise des particules métalliques pour réparer les blessures',
                'hit' => 100,
                'level' => 3,
            ],
            'blade_barrier' => [
                'slug' => 'blade-barrier',
                'damage' => 3,
                'element' => Element::Metal,
                'heal' => 3,
                'name' => 'Barrière de lames',
                'description' => 'Crée une barrière de lames tournoyantes qui protège et attaque',
                'hit' => 90,
                'level' => 2,
            ],
            'silver_bolt' => [
                'slug' => 'silver-bolt',
                'damage' => 6,
                'element' => Element::Metal,
                'heal' => null,
                'name' => 'Carreau d\'argent',
                'description' => 'Un projectile d\'argent pur qui transperce les défenses',
                'hit' => 85,
                'level' => 3,
            ],
            'crushing_weight' => [
                'slug' => 'crushing-weight',
                'damage' => 7,
                'element' => Element::Metal,
                'heal' => null,
                'name' => 'Poids écrasant',
                'description' => 'Une masse métallique qui s\'abat sur l\'ennemi',
                'hit' => 80,
                'level' => 4,
            ],
            'magnetic_pull' => [
                'slug' => 'magnetic-pull',
                'damage' => 2,
                'element' => Element::Metal,
                'heal' => null,
                'name' => 'Attraction magnétique',
                'description' => 'Attire violemment les objets métalliques vers l\'ennemi',
                'hit' => 95,
                'level' => 1,
            ],

            // Sorts de nature
            'liana_whip' => [
                'slug' => 'liana-whip',
                'damage' => 1,
                'element' => Element::Beast,
                'heal' => null,
                'name' => 'Liane',
                'description' => 'Des lianes fouettent l\'ennemi',
                'hit' => 90,
                'energyCost' => 4,
                'level' => 1,
            ],
            'thorn_burst' => [
                'slug' => 'thorn-burst',
                'damage' => 3,
                'element' => Element::Beast,
                'heal' => null,
                'name' => 'Explosion d\'épines',
                'description' => 'Des épines jaillissent du sol et blessent les ennemis',
                'hit' => 85,
                'level' => 2,
            ],
            'natural_healing' => [
                'slug' => 'natural-healing',
                'damage' => null,
                'element' => Element::Beast,
                'heal' => 4,
                'name' => 'Guérison naturelle',
                'description' => 'Les forces de la nature soignent les blessures',
                'hit' => 100,
                'level' => 1,
            ],
            'poison_cloud' => [
                'slug' => 'poison-cloud',
                'damage' => 4,
                'element' => Element::Beast,
                'heal' => null,
                'name' => 'Empoisonnement',
                'description' => 'Un nuage de spores toxiques qui empoisonne l\'ennemi',
                'hit' => 85,
                'energyCost' => 10,
                'statusEffectSlug' => 'poison',
                'level' => 3,
            ],
            'entangling_roots' => [
                'slug' => 'entangling-roots',
                'damage' => 2,
                'element' => Element::Beast,
                'heal' => null,
                'name' => 'Racines enchevetrees',
                'description' => 'Des racines surgissent du sol et immobilisent l\'ennemi',
                'hit' => 95,
                'statusEffectSlug' => 'paralysis',
                'level' => 2,
            ],
            'nature_wrath' => [
                'slug' => 'nature-wrath',
                'damage' => 6,
                'element' => Element::Beast,
                'heal' => null,
                'name' => 'Appel de la foret',
                'description' => 'Dechaine la fureur de la nature sur l\'ennemi',
                'hit' => 80,
                'energyCost' => 20,
                'cooldown' => 3,
                'statusEffectSlug' => 'poison-strong',
                'aoeTargets' => 0,
                'level' => 4,
            ],
            'leaf_blade' => [
                'slug' => 'leaf-blade',
                'damage' => 5,
                'element' => Element::Beast,
                'heal' => null,
                'name' => 'Lame feuille',
                'description' => 'Une lame tranchante formée de feuilles acérées',
                'hit' => 90,
                'level' => 3,
            ],
            'forest_embrace' => [
                'slug' => 'forest-embrace',
                'damage' => null,
                'element' => Element::Beast,
                'heal' => 7,
                'name' => 'Étreinte de la forêt',
                'description' => 'L\'énergie de la forêt enveloppe et soigne les blessures',
                'hit' => 100,
                'level' => 3,
            ],
            'venomous_bite' => [
                'slug' => 'venomous-bite',
                'damage' => 3,
                'element' => Element::Beast,
                'heal' => null,
                'name' => 'Morsure venimeuse',
                'description' => 'Une morsure qui injecte un venin puissant',
                'hit' => 90,
                'level' => 2,
            ],
            'wild_growth' => [
                'slug' => 'wild-growth',
                'damage' => 1,
                'element' => Element::Beast,
                'heal' => 5,
                'name' => 'Croissance sauvage',
                'description' => 'Des plantes médicinales poussent rapidement et soignent les blessures',
                'hit' => 100,
                'level' => 2,
            ],
            'nature_fury' => [
                'slug' => 'nature-fury',
                'damage' => 8,
                'element' => Element::Beast,
                'heal' => null,
                'name' => 'Fureur naturelle',
                'description' => 'Libère toute la puissance destructrice de la nature',
                'hit' => 75,
                'level' => 5,
            ],
            'thorn_shield' => [
                'slug' => 'thorn-shield',
                'damage' => 2,
                'element' => Element::Beast,
                'heal' => 3,
                'name' => 'Bouclier d\'épines',
                'description' => 'Un bouclier d\'épines qui protège et blesse les attaquants',
                'hit' => 100,
                'level' => 2,
            ],
            'toxic_spores' => [
                'slug' => 'toxic-spores',
                'damage' => 4,
                'element' => Element::Beast,
                'heal' => null,
                'name' => 'Spores toxiques',
                'description' => 'Libère des spores hautement toxiques dans l\'air',
                'hit' => 85,
                'level' => 2,
            ],
            'nature_blessing' => [
                'slug' => 'nature-blessing',
                'damage' => null,
                'element' => Element::Beast,
                'heal' => 10,
                'name' => 'Bénédiction de la nature',
                'description' => 'La bénédiction de la nature qui restaure la vitalité',
                'hit' => 100,
                'level' => 4,
            ],
            'vine_snare' => [
                'slug' => 'vine-snare',
                'damage' => 3,
                'element' => Element::Beast,
                'heal' => null,
                'name' => 'Piège de vignes',
                'description' => 'Des vignes surgissent et s\'enroulent autour de l\'ennemi',
                'hit' => 90,
                'level' => 2,
            ],
            'primal_surge' => [
                'slug' => 'primal-surge',
                'damage' => 5,
                'element' => Element::Beast,
                'heal' => 5,
                'name' => 'Afflux primordial',
                'description' => 'Un afflux d\'énergie primordiale qui soigne et blesse',
                'hit' => 85,
                'level' => 4,
            ],

            // Sorts de vent
            'wind_lame' => [
                'slug' => 'wind-lame',
                'damage' => 1,
                'element' => Element::Air,
                'heal' => null,
                'name' => "Lame d'air",
                'description' => "une lame d'air tranchante",
                'hit' => 90,
                'level' => 1,
            ],
            'tornado' => [
                'slug' => 'tornado',
                'damage' => 4,
                'element' => Element::Air,
                'heal' => null,
                'name' => 'Tornade',
                'description' => 'Une violente tornade qui emporte tout sur son passage',
                'hit' => 80,
                'level' => 2,
            ],
            'wind_shield' => [
                'slug' => 'wind-shield',
                'damage' => 0,
                'element' => Element::Air,
                'heal' => 2,
                'name' => 'Bouclier de vent',
                'description' => 'Un tourbillon protecteur qui dévie les attaques',
                'hit' => 100,
                'level' => 1,
            ],
            'gust' => [
                'slug' => 'gust',
                'damage' => 2,
                'element' => Element::Air,
                'heal' => null,
                'name' => 'Bourrasque',
                'description' => 'Une puissante bourrasque qui repousse l\'ennemi',
                'hit' => 95,
                'level' => 1,
            ],
            'air_dash' => [
                'slug' => 'air-dash',
                'damage' => 1,
                'element' => Element::Air,
                'heal' => 1,
                'name' => 'Ruée d\'air',
                'description' => 'Permet de se déplacer rapidement sur un coussin d\'air',
                'hit' => 100,
                'level' => 1,
            ],
            'air_slash' => [
                'slug' => 'air-slash',
                'damage' => 5,
                'element' => Element::Air,
                'heal' => null,
                'name' => 'Tranchant aérien',
                'description' => 'Une lame d\'air comprimé qui tranche l\'ennemi',
                'hit' => 85,
                'level' => 3,
            ],
            'cyclone' => [
                'slug' => 'cyclone',
                'damage' => 6,
                'element' => Element::Air,
                'heal' => null,
                'name' => 'Cyclone',
                'description' => 'Un puissant cyclone qui déchire tout sur son passage',
                'hit' => 80,
                'level' => 3,
            ],
            'wind_blast' => [
                'slug' => 'wind-blast',
                'damage' => 3,
                'element' => Element::Air,
                'heal' => null,
                'name' => 'Souffle du vent',
                'description' => 'Une rafale concentrée qui frappe l\'ennemi',
                'hit' => 90,
                'level' => 2,
            ],
            'healing_breeze' => [
                'slug' => 'healing-breeze',
                'damage' => null,
                'element' => Element::Air,
                'heal' => 5,
                'name' => 'Brise guérisseuse',
                'description' => 'Une douce brise qui apaise et soigne les blessures',
                'hit' => 100,
                'level' => 2,
            ],
            'vacuum_blade' => [
                'slug' => 'vacuum-blade',
                'damage' => 7,
                'element' => Element::Air,
                'heal' => null,
                'name' => 'Lame de vide',
                'description' => 'Une lame créée par le vide qui tranche tout',
                'hit' => 75,
                'level' => 4,
            ],
            'wind_wall' => [
                'slug' => 'wind-wall',
                'damage' => 1,
                'element' => Element::Air,
                'heal' => 4,
                'name' => 'Mur de vent',
                'description' => 'Un mur de vent qui protège et repousse les attaques',
                'hit' => 100,
                'level' => 2,
            ],
            'hurricane' => [
                'slug' => 'hurricane',
                'damage' => 8,
                'element' => Element::Air,
                'heal' => null,
                'name' => 'Ouragan',
                'description' => 'Un ouragan dévastateur qui ravage tout',
                'hit' => 70,
                'level' => 5,
            ],
            'air_current' => [
                'slug' => 'air-current',
                'damage' => 2,
                'element' => Element::Air,
                'heal' => 3,
                'name' => 'Courant d\'air',
                'description' => 'Un courant d\'air revigorant qui soigne et protège',
                'hit' => 95,
                'level' => 1,
            ],
            'pressure_point' => [
                'slug' => 'pressure-point',
                'damage' => 4,
                'element' => Element::Air,
                'heal' => null,
                'name' => 'Point de pression',
                'description' => 'Concentre l\'air sur un point précis pour causer des dégâts internes',
                'hit' => 90,
                'level' => 2,
            ],
            'wind_scythe' => [
                'slug' => 'wind-scythe',
                'damage' => 6,
                'element' => Element::Air,
                'heal' => null,
                'name' => 'Faux de vent',
                'description' => 'Une faux d\'air tranchante qui fauche les ennemis',
                'hit' => 85,
                'level' => 3,
            ],
            'tempest' => [
                'slug' => 'tempest',
                'damage' => 5,
                'element' => Element::Air,
                'heal' => null,
                'name' => 'Tempête',
                'description' => 'Une violente tempête qui frappe de toutes parts',
                'hit' => 85,
                'level' => 3,
            ],
            'wind_blessing' => [
                'slug' => 'wind-blessing',
                'damage' => null,
                'element' => Element::Air,
                'heal' => 7,
                'name' => 'Bénédiction du vent',
                'description' => 'La bénédiction des vents qui soigne et revigore',
                'hit' => 100,
                'level' => 3,
            ],

            // Sorts sans élément
            'none_attack_1' => [
                'slug' => 'none-attack-1',
                'damage' => 1,
                'element' => Element::None,
                'heal' => null,
                'name' => 'Attaque',
                'description' => 'Attaque 1',
                'hit' => 90,
                'level' => 1,
            ],
            'none_attack_2' => [
                'slug' => 'none-attack-2',
                'damage' => 2,
                'element' => Element::None,
                'heal' => null,
                'name' => 'Attaque',
                'description' => 'Attaque 2',
                'hit' => 90,
                'level' => 1,
            ],
            'none_heal_2' => [
                'slug' => 'none-heal-2',
                'damage' => null,
                'element' => Element::None,
                'heal' => 2,
                'name' => 'Soin',
                'description' => 'Soin 2',
                'hit' => 90,
                'level' => 1,
            ],
        ];
    }
}
