<?php

namespace App\DataFixtures;

use App\Entity\Game\Spell;
use App\Enum\Element;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;

class SpellFixtures extends Fixture
{
    public function load(ObjectManager $manager): void
    {
        $spellsData = $this->getSpellsData();

        // Création des sorts pour chaque élément
        foreach ($spellsData as $key => $data) {
            $spell = new Spell();
            $spell->setSlug($data['slug']);
            $spell->setDamage($data['damage']);
            $spell->setElement($data['element']);
            $spell->setHeal($data['heal']);
            $spell->setName($data['name']);
            $spell->setDescription($data['description']);
            $spell->setHit($data['hit'] ?? 90);
            $spell->setCritical($data['critical'] ?? 5);
            $spell->setEnergyCost($data['energyCost'] ?? 0);
            $spell->setCooldown($data['cooldown'] ?? null);
            $spell->setStatusEffectSlug($data['statusEffectSlug'] ?? null);
            $spell->setAoeTargets($data['aoeTargets'] ?? 1);
            $spell->setLevel($data['level'] ?? 1);
            $spell->setValueType($data['valueType'] ?? 'fixed');
            $spell->setCreatedAt(new \DateTime());
            $spell->setUpdatedAt(new \DateTime());

            $manager->persist($spell);
            $this->addReference($key, $spell);
        }

        $manager->flush();
    }

    /**
     * Retourne les données des sorts.
     */
    private function getSpellsData(): array
    {
        return [
            // Sorts de feu
            'fire_ball' => [
                'slug' => 'fire-ball',
                'damage' => 2,
                'element' => Element::Fire,
                'heal' => null,
                'name' => 'Boule de feu',
                'description' => 'Une boule de feu pour tout cramer',
                'hit' => 90,
                'energyCost' => 5,
                'statusEffectSlug' => 'burn',
                'critical' => 8,
                'level' => 1,
            ],
            'flame' => [
                'slug' => 'flame',
                'damage' => 1,
                'element' => Element::Fire,
                'heal' => null,
                'name' => 'Flammèche',
                'description' => 'Un sort de flammèche',
                'hit' => 90,
                'level' => 1,
            ],
            'flamer' => [
                'slug' => 'flamer',
                'damage' => 3,
                'element' => Element::Fire,
                'heal' => null,
                'name' => 'Feu',
                'description' => 'Un sort de feu',
                'hit' => 90,
                'level' => 2,
            ],
            'flame_rain' => [
                'slug' => 'flame-rain',
                'damage' => 5,
                'element' => Element::Fire,
                'heal' => null,
                'name' => 'Pluie de flammes',
                'description' => 'Une pluie de flammes qui carbonise tout sur une large zone',
                'hit' => 85,
                'energyCost' => 12,
                'cooldown' => 2,
                'statusEffectSlug' => 'burn',
                'critical' => 10,
                'aoeTargets' => 0,
                'level' => 3,
            ],
            'inferno' => [
                'slug' => 'inferno',
                'damage' => 7,
                'element' => Element::Fire,
                'heal' => null,
                'name' => 'Inferno',
                'description' => 'Un brasier dévastateur qui consume tout sur son passage',
                'hit' => 85,
                'energyCost' => 20,
                'cooldown' => 3,
                'statusEffectSlug' => 'burn',
                'critical' => 12,
                'aoeTargets' => 0,
                'level' => 4,
            ],
            'fire_wall' => [
                'slug' => 'fire-wall',
                'damage' => 4,
                'element' => Element::Fire,
                'heal' => null,
                'name' => 'Mur de feu',
                'description' => 'Crée un mur de flammes infranchissable',
                'hit' => 95,
                'level' => 2,
            ],
            'fire_nova' => [
                'slug' => 'fire-nova',
                'damage' => 6,
                'element' => Element::Fire,
                'heal' => null,
                'name' => 'Nova de feu',
                'description' => 'Une explosion de feu qui se propage dans toutes les directions',
                'hit' => 85,
                'level' => 3,
            ],
            'phoenix_flame' => [
                'slug' => 'phoenix-flame',
                'damage' => 5,
                'element' => Element::Fire,
                'heal' => 2,
                'name' => 'Flamme du phénix',
                'description' => 'Des flammes régénératrices qui brûlent et soignent à la fois',
                'hit' => 90,
                'level' => 3,
            ],
            'meteor_strike' => [
                'slug' => 'meteor-strike',
                'damage' => 8,
                'element' => Element::Fire,
                'heal' => null,
                'name' => 'Frappe météorique',
                'description' => 'Invoque un météore enflammé qui s\'écrase sur l\'ennemi',
                'hit' => 75,
                'level' => 4,
            ],
            'burning_touch' => [
                'slug' => 'burning-touch',
                'damage' => 2,
                'element' => Element::Fire,
                'heal' => null,
                'name' => 'Toucher brûlant',
                'description' => 'Un simple contact qui inflige des brûlures',
                'hit' => 100,
                'level' => 1,
            ],
            'heat_wave' => [
                'slug' => 'heat-wave',
                'damage' => 3,
                'element' => Element::Fire,
                'heal' => null,
                'name' => 'Vague de chaleur',
                'description' => 'Une onde de chaleur qui affaiblit les ennemis',
                'hit' => 95,
                'level' => 2,
            ],
            'dragon_breath' => [
                'slug' => 'dragon-breath',
                'damage' => 6,
                'element' => Element::Fire,
                'heal' => null,
                'name' => 'Souffle du dragon',
                'description' => 'Un souffle de feu devastateur',
                'hit' => 85,
                'statusEffectSlug' => 'burn',
                'aoeTargets' => 0,
                'critical' => 10,
                'level' => 4,
            ],
            'volcanic_eruption' => [
                'slug' => 'volcanic-eruption',
                'damage' => 10,
                'element' => Element::Fire,
                'heal' => null,
                'name' => 'Eruption volcanique',
                'description' => 'Dechaine la puissance d\'un volcan sur les ennemis',
                'hit' => 70,
                'energyCost' => 30,
                'cooldown' => 5,
                'statusEffectSlug' => 'burn',
                'critical' => 15,
                'aoeTargets' => 0,
                'level' => 5,
            ],
            'ember_shield' => [
                'slug' => 'ember-shield',
                'damage' => 1,
                'element' => Element::Fire,
                'heal' => 3,
                'name' => 'Bouclier d\'étincelles',
                'description' => 'Un bouclier de braises qui protège et brûle les attaquants',
                'hit' => 100,
                'level' => 2,
            ],
            'fire_whip' => [
                'slug' => 'fire-whip',
                'damage' => 4,
                'element' => Element::Fire,
                'heal' => null,
                'name' => 'Fouet de feu',
                'description' => 'Un fouet enflammé qui frappe à distance',
                'hit' => 90,
                'level' => 2,
            ],
            'combustion' => [
                'slug' => 'combustion',
                'damage' => 3,
                'element' => Element::Fire,
                'heal' => null,
                'name' => 'Combustion',
                'description' => 'Enflamme instantanément la cible',
                'hit' => 95,
                'level' => 2,
            ],

            // Sorts de vie
            'life_heal' => [
                'slug' => 'life-heal',
                'damage' => null,
                'element' => Element::Light,
                'heal' => 5,
                'name' => 'Soin mineur',
                'description' => 'Un soin mineur qui fait du bien',
                'hit' => 100,
                'energyCost' => 5,
                'level' => 1,
            ],
            'rejuvenation' => [
                'slug' => 'rejuvenation',
                'damage' => null,
                'element' => Element::Light,
                'heal' => 8,
                'name' => 'Regeneration',
                'description' => 'Un sort de regeneration qui restaure progressivement la sante',
                'hit' => 100,
                'energyCost' => 10,
                'statusEffectSlug' => 'regeneration',
                'level' => 2,
            ],
            'divine_blessing' => [
                'slug' => 'divine-blessing',
                'damage' => null,
                'element' => Element::Light,
                'heal' => 12,
                'name' => 'Benediction divine',
                'description' => 'Une puissante benediction qui soigne les blessures graves',
                'hit' => 100,
                'energyCost' => 18,
                'cooldown' => 3,
                'statusEffectSlug' => 'regeneration-strong',
                'level' => 4,
            ],
            'healing_wave' => [
                'slug' => 'healing-wave',
                'damage' => null,
                'element' => Element::Light,
                'heal' => 7,
                'name' => 'Vague de guérison',
                'description' => 'Une vague d\'énergie curative qui soigne les blessures',
                'hit' => 100,
                'level' => 2,
            ],
            'life_transfer' => [
                'slug' => 'life-transfer',
                'damage' => 2,
                'element' => Element::Light,
                'heal' => 4,
                'name' => 'Transfert de vie',
                'description' => 'Transfère l\'énergie vitale de l\'ennemi vers soi',
                'hit' => 90,
                'level' => 2,
            ],
            'holy_light' => [
                'slug' => 'holy-light',
                'damage' => 3,
                'element' => Element::Light,
                'heal' => 3,
                'name' => 'Lumiere',
                'description' => 'Une lumiere divine qui soigne les allies et blesse les ennemis',
                'hit' => 95,
                'energyCost' => 6,
                'level' => 2,
            ],
            'vitality_surge' => [
                'slug' => 'vitality-surge',
                'damage' => null,
                'element' => Element::Light,
                'heal' => 10,
                'name' => 'Afflux de vitalité',
                'description' => 'Un puissant afflux d\'énergie vitale qui restaure la santé',
                'hit' => 100,
                'level' => 3,
            ],
            'life_shield' => [
                'slug' => 'life-shield',
                'damage' => null,
                'element' => Element::Light,
                'heal' => 6,
                'name' => 'Bouclier de vie',
                'description' => 'Crée un bouclier protecteur qui absorbe les dégâts',
                'hit' => 100,
                'level' => 2,
            ],
            'angelic_touch' => [
                'slug' => 'angelic-touch',
                'damage' => null,
                'element' => Element::Light,
                'heal' => 4,
                'name' => 'Toucher angélique',
                'description' => 'Un toucher qui apaise les blessures',
                'hit' => 100,
                'level' => 1,
            ],
            'purification' => [
                'slug' => 'purification',
                'damage' => 1,
                'element' => Element::Light,
                'heal' => 5,
                'name' => 'Purification',
                'description' => 'Purifie le corps et l\'esprit, eliminant les afflictions',
                'hit' => 100,
                'energyCost' => 10,
                'level' => 3,
            ],
            'celestial_blessing' => [
                'slug' => 'celestial-blessing',
                'damage' => null,
                'element' => Element::Light,
                'heal' => 15,
                'name' => 'Bénédiction céleste',
                'description' => 'Une bénédiction des cieux qui restaure une grande quantité de santé',
                'hit' => 95,
                'level' => 5,
            ],
            'life_burst' => [
                'slug' => 'life-burst',
                'damage' => null,
                'element' => Element::Light,
                'heal' => 9,
                'name' => 'Explosion de vie',
                'description' => 'Une explosion d\'énergie vitale qui soigne instantanément',
                'hit' => 100,
                'level' => 3,
            ],
            'divine_intervention' => [
                'slug' => 'divine-intervention',
                'damage' => 5,
                'element' => Element::Light,
                'heal' => 5,
                'name' => 'Jugement sacre',
                'description' => 'Un jugement divin qui soigne les allies et punit les ennemis',
                'hit' => 90,
                'energyCost' => 22,
                'cooldown' => 4,
                'critical' => 15,
                'level' => 5,
            ],
            'healing_touch' => [
                'slug' => 'healing-touch',
                'damage' => null,
                'element' => Element::Light,
                'heal' => 3,
                'name' => 'Toucher guérisseur',
                'description' => 'Un simple toucher qui soigne les blessures légères',
                'hit' => 100,
                'level' => 1,
            ],
            'life_bloom' => [
                'slug' => 'life-bloom',
                'damage' => null,
                'element' => Element::Light,
                'heal' => 6,
                'name' => 'Floraison de vie',
                'description' => 'Une énergie vitale qui se répand progressivement',
                'hit' => 100,
                'level' => 2,
            ],
            'sacred_light' => [
                'slug' => 'sacred-light',
                'damage' => 4,
                'element' => Element::Light,
                'heal' => 2,
                'name' => 'Lumière sacrée',
                'description' => 'Un rayon de lumière divine qui purifie et soigne',
                'hit' => 95,
                'level' => 2,
            ],

            // Sorts de mort
            'punishment' => [
                'slug' => 'punishment',
                'damage' => 1,
                'element' => Element::Dark,
                'heal' => null,
                'name' => 'Châtiment',
                'description' => 'Un sort de châtiment',
                'hit' => 90,
                'level' => 1,
            ],
            'soul_drain' => [
                'slug' => 'soul-drain',
                'damage' => 3,
                'element' => Element::Dark,
                'heal' => 1,
                'name' => 'Drain de vie',
                'description' => 'Aspire l\'energie vitale de la cible pour se soigner',
                'hit' => 85,
                'energyCost' => 6,
                'level' => 2,
            ],
            'death_touch' => [
                'slug' => 'death-touch',
                'damage' => 4,
                'element' => Element::Dark,
                'heal' => null,
                'name' => 'Toucher mortel',
                'description' => 'Un contact qui inflige une douleur intense',
                'hit' => 80,
                'level' => 2,
            ],
            'shadow_bolt' => [
                'slug' => 'shadow-bolt',
                'damage' => 5,
                'element' => Element::Dark,
                'heal' => null,
                'name' => 'Éclair d\'ombre',
                'description' => 'Un projectile d\'énergie sombre qui frappe la cible',
                'hit' => 85,
                'level' => 3,
            ],
            'life_leech' => [
                'slug' => 'life-leech',
                'damage' => 4,
                'element' => Element::Dark,
                'heal' => 2,
                'name' => 'Sangsue vitale',
                'description' => 'Absorbe l\'énergie vitale de la cible',
                'hit' => 90,
                'level' => 2,
            ],
            'death_grip' => [
                'slug' => 'death-grip',
                'damage' => 3,
                'element' => Element::Dark,
                'heal' => null,
                'name' => 'Emprise de la mort',
                'description' => 'Une main spectrale qui saisit et blesse la cible',
                'hit' => 95,
                'level' => 2,
            ],
            'shadow_wave' => [
                'slug' => 'shadow-wave',
                'damage' => 6,
                'element' => Element::Dark,
                'heal' => null,
                'name' => 'Vague d\'ombre',
                'description' => 'Une vague d\'énergie sombre qui balaye la zone',
                'hit' => 80,
                'level' => 3,
            ],
            'necrotic_touch' => [
                'slug' => 'necrotic-touch',
                'damage' => 2,
                'element' => Element::Dark,
                'heal' => null,
                'name' => 'Toucher nécrotique',
                'description' => 'Un toucher qui provoque la nécrose des tissus',
                'hit' => 100,
                'level' => 1,
            ],
            'dark_harvest' => [
                'slug' => 'dark-harvest',
                'damage' => 7,
                'element' => Element::Dark,
                'heal' => 3,
                'name' => 'Moisson sombre',
                'description' => 'Recolte l\'energie vitale des ennemis affaiblis',
                'hit' => 75,
                'energyCost' => 18,
                'cooldown' => 3,
                'statusEffectSlug' => 'poison-strong',
                'critical' => 12,
                'level' => 4,
            ],
            'soul_rip' => [
                'slug' => 'soul-rip',
                'damage' => 8,
                'element' => Element::Dark,
                'heal' => null,
                'name' => 'Déchirure d\'âme',
                'description' => 'Déchire l\'âme de la cible, causant une douleur intense',
                'hit' => 70,
                'level' => 4,
            ],
            'death_nova' => [
                'slug' => 'death-nova',
                'damage' => 6,
                'element' => Element::Dark,
                'heal' => null,
                'name' => 'Nova de mort',
                'description' => 'Une explosion d\'énergie mortelle qui se propage',
                'hit' => 80,
                'level' => 3,
            ],
            'shadow_mend' => [
                'slug' => 'shadow-mend',
                'damage' => 1,
                'element' => Element::Dark,
                'heal' => 5,
                'name' => 'Guérison des ombres',
                'description' => 'Utilise l\'énergie sombre pour soigner les blessures',
                'hit' => 95,
                'level' => 2,
            ],
            'plague_strike' => [
                'slug' => 'plague-strike',
                'damage' => 3,
                'element' => Element::Dark,
                'heal' => null,
                'name' => 'Malediction',
                'description' => 'Maudit la cible, empoisonnant son corps et son ame',
                'hit' => 90,
                'energyCost' => 10,
                'statusEffectSlug' => 'poison',
                'level' => 3,
            ],
            'death_coil' => [
                'slug' => 'death-coil',
                'damage' => 5,
                'element' => Element::Dark,
                'heal' => null,
                'name' => 'Spirale de mort',
                'description' => 'Une spirale d\'énergie nécrotique qui frappe la cible',
                'hit' => 85,
                'level' => 3,
            ],
            'soul_siphon' => [
                'slug' => 'soul-siphon',
                'damage' => 4,
                'element' => Element::Dark,
                'heal' => 4,
                'name' => 'Siphon d\'âme',
                'description' => 'Siphonne l\'essence vitale de la cible',
                'hit' => 85,
                'level' => 3,
            ],
            'dark_ritual' => [
                'slug' => 'dark-ritual',
                'damage' => 2,
                'element' => Element::Dark,
                'heal' => 6,
                'name' => 'Rituel sombre',
                'description' => 'Un rituel qui sacrifie une partie de sa force pour se soigner',
                'hit' => 100,
                'level' => 3,
            ],

            // Sorts de terre
            'stone_throw' => [
                'slug' => 'stone-throw',
                'damage' => 1,
                'element' => Element::Earth,
                'heal' => null,
                'name' => 'Jet de cailloux',
                'description' => 'Un sort de jet de cailloux',
                'hit' => 90,
                'level' => 1,
            ],
            'earthquake' => [
                'slug' => 'earthquake',
                'damage' => 4,
                'element' => Element::Earth,
                'heal' => null,
                'name' => 'Tremblement de terre',
                'description' => 'Provoque un séisme qui déstabilise les ennemis',
                'hit' => 85,
                'level' => 2,
            ],
            'rock_armor' => [
                'slug' => 'rock-armor',
                'damage' => 0,
                'element' => Element::Earth,
                'heal' => 3,
                'name' => 'Parade',
                'description' => 'Une parade rocheuse qui absorbe les degats',
                'hit' => 100,
                'energyCost' => 5,
                'statusEffectSlug' => 'shield',
                'level' => 1,
            ],
            'boulder_throw' => [
                'slug' => 'boulder-throw',
                'damage' => 6,
                'element' => Element::Earth,
                'heal' => null,
                'name' => 'Lancer de rocher',
                'description' => 'Lance un énorme rocher sur l\'ennemi',
                'hit' => 80,
                'level' => 3,
            ],
            'earth_spike' => [
                'slug' => 'earth-spike',
                'damage' => 3,
                'element' => Element::Earth,
                'heal' => null,
                'name' => 'Pic de terre',
                'description' => 'Un pic rocheux jaillit du sol et transperce l\'ennemi',
                'hit' => 90,
                'level' => 2,
            ],
            'stone_spikes' => [
                'slug' => 'stone-spikes',
                'damage' => 4,
                'element' => Element::Earth,
                'heal' => null,
                'name' => 'Pics de pierre',
                'description' => 'Fait jaillir plusieurs pics de pierre acérés du sol',
                'hit' => 88,
                'level' => 2,
            ],
            'landslide' => [
                'slug' => 'landslide',
                'damage' => 5,
                'element' => Element::Earth,
                'heal' => null,
                'name' => 'Glissement de terrain',
                'description' => 'Déclenche un glissement de terrain qui ensevelit les ennemis',
                'hit' => 85,
                'level' => 3,
            ],
            'stone_skin' => [
                'slug' => 'stone-skin',
                'damage' => 0,
                'element' => Element::Earth,
                'heal' => 5,
                'name' => 'Bouclier magique',
                'description' => 'Un bouclier de pierre magique offrant une protection accrue',
                'hit' => 100,
                'energyCost' => 10,
                'statusEffectSlug' => 'shield-strong',
                'level' => 3,
            ],
            'earth_shield' => [
                'slug' => 'earth-shield',
                'damage' => 1,
                'element' => Element::Earth,
                'heal' => 4,
                'name' => 'Bouclier terreux',
                'description' => 'Un bouclier de terre qui protège et contre-attaque',
                'hit' => 100,
                'level' => 2,
            ],
            'crystal_spear' => [
                'slug' => 'crystal-spear',
                'damage' => 7,
                'element' => Element::Earth,
                'heal' => null,
                'name' => 'Lance de cristal',
                'description' => 'Une lance de cristal tranchante qui transperce les armures',
                'hit' => 85,
                'level' => 4,
            ],
            'quicksand' => [
                'slug' => 'quicksand',
                'damage' => 2,
                'element' => Element::Earth,
                'heal' => null,
                'name' => 'Sables mouvants',
                'description' => 'Transforme le sol en sables mouvants qui engloutissent l\'ennemi',
                'hit' => 95,
                'level' => 1,
            ],
            'stone_wall' => [
                'slug' => 'stone-wall',
                'damage' => 0,
                'element' => Element::Earth,
                'heal' => 6,
                'name' => 'Mur de fer',
                'description' => 'Erige un mur de fer infranchissable',
                'hit' => 100,
                'energyCost' => 20,
                'cooldown' => 4,
                'statusEffectSlug' => 'shield-strong',
                'level' => 4,
            ],
            'earth_blessing' => [
                'slug' => 'earth-blessing',
                'damage' => 0,
                'element' => Element::Earth,
                'heal' => 8,
                'name' => 'Bénédiction de la terre',
                'description' => 'Invoque la bénédiction de la terre pour soigner et protéger',
                'hit' => 100,
                'level' => 3,
            ],
            'mountain_strength' => [
                'slug' => 'mountain-strength',
                'damage' => 3,
                'element' => Element::Earth,
                'heal' => 3,
                'name' => 'Force de la montagne',
                'description' => 'Puise dans la force des montagnes pour renforcer le corps',
                'hit' => 95,
                'level' => 2,
            ],
            'crystal_growth' => [
                'slug' => 'crystal-growth',
                'damage' => 4,
                'element' => Element::Earth,
                'heal' => null,
                'name' => 'Croissance cristalline',
                'description' => 'Des cristaux acérés poussent rapidement et blessent l\'ennemi',
                'hit' => 90,
                'level' => 2,
            ],
            'tectonic_shift' => [
                'slug' => 'tectonic-shift',
                'damage' => 8,
                'element' => Element::Earth,
                'heal' => null,
                'name' => 'Déplacement tectonique',
                'description' => 'Provoque un violent déplacement des plaques tectoniques',
                'hit' => 75,
                'level' => 5,
            ],
            'petrification' => [
                'slug' => 'petrification',
                'damage' => 5,
                'element' => Element::Earth,
                'heal' => null,
                'name' => 'Pétrification',
                'description' => 'Transforme partiellement l\'ennemi en pierre',
                'hit' => 80,
                'level' => 3,
            ],

            // Sorts de métal
            'sword_10' => [
                'slug' => 'slug-10',
                'damage' => 1,
                'element' => Element::Metal,
                'heal' => null,
                'name' => "Coup d'épée",
                'description' => "Un coup d'épée neutre",
                'hit' => 90,
                'level' => 1,
            ],
            'sharp_blade' => [
                'slug' => 'sharp-blade',
                'damage' => 1,
                'element' => Element::Metal,
                'heal' => null,
                'name' => 'Frappe puissante',
                'description' => 'Une frappe puissante avec une lame tranchante',
                'hit' => 95,
                'energyCost' => 4,
                'critical' => 10,
                'level' => 1,
            ],
            'metal_storm' => [
                'slug' => 'metal-storm',
                'damage' => 5,
                'element' => Element::Metal,
                'heal' => null,
                'name' => 'Tempête métallique',
                'description' => 'Une pluie de fragments métalliques acérés',
                'hit' => 80,
                'level' => 3,
            ],
            'iron_fist' => [
                'slug' => 'iron-fist',
                'damage' => 3,
                'element' => Element::Metal,
                'heal' => null,
                'name' => 'Charge',
                'description' => 'Une charge brutale avec un poing de fer',
                'hit' => 90,
                'energyCost' => 8,
                'critical' => 12,
                'level' => 2,
            ],
            'blade_dance' => [
                'slug' => 'blade-dance',
                'damage' => 6,
                'element' => Element::Metal,
                'heal' => null,
                'name' => 'Tourbillon d\'epee',
                'description' => 'Un tourbillon devastateur de lames qui frappe tous les ennemis',
                'hit' => 85,
                'energyCost' => 15,
                'cooldown' => 2,
                'critical' => 15,
                'aoeTargets' => 0,
                'level' => 4,
            ],
            'steel_shield' => [
                'slug' => 'steel-shield',
                'damage' => 0,
                'element' => Element::Metal,
                'heal' => 4,
                'name' => 'Bouclier d\'acier',
                'description' => 'Un bouclier métallique qui offre une protection solide',
                'hit' => 100,
                'level' => 2,
            ],
            'razor_edge' => [
                'slug' => 'razor-edge',
                'damage' => 7,
                'element' => Element::Metal,
                'heal' => null,
                'name' => 'Lame rasoir',
                'description' => 'Une lame si fine qu\'elle coupe presque tout',
                'hit' => 80,
                'level' => 4,
            ],
            'metal_skin' => [
                'slug' => 'metal-skin',
                'damage' => 1,
                'element' => Element::Metal,
                'heal' => 5,
                'name' => 'Peau métallique',
                'description' => 'Transforme la peau en métal pour une protection accrue',
                'hit' => 100,
                'level' => 3,
            ],
            'shrapnel_burst' => [
                'slug' => 'shrapnel-burst',
                'damage' => 4,
                'element' => Element::Metal,
                'heal' => null,
                'name' => 'Explosion d\'éclats',
                'description' => 'Une explosion qui projette des éclats métalliques dans toutes les directions',
                'hit' => 85,
                'level' => 2,
            ],
            'iron_maiden' => [
                'slug' => 'iron-maiden',
                'damage' => 8,
                'element' => Element::Metal,
                'heal' => null,
                'name' => 'Vierge de fer',
                'description' => 'Emprisonne l\'ennemi dans une cage de pointes métalliques',
                'hit' => 75,
                'level' => 5,
            ],
            'chain_lightning' => [
                'slug' => 'chain-lightning',
                'damage' => 5,
                'element' => Element::Metal,
                'heal' => null,
                'name' => 'Chaîne d\'éclairs',
                'description' => 'Des chaînes métalliques chargées d\'électricité frappent l\'ennemi',
                'hit' => 85,
                'level' => 3,
            ],
            'metallic_regeneration' => [
                'slug' => 'metallic-regeneration',
                'damage' => 0,
                'element' => Element::Metal,
                'heal' => 6,
                'name' => 'Régénération métallique',
                'description' => 'Utilise des particules métalliques pour réparer les blessures',
                'hit' => 100,
                'level' => 3,
            ],
            'blade_barrier' => [
                'slug' => 'blade-barrier',
                'damage' => 3,
                'element' => Element::Metal,
                'heal' => 3,
                'name' => 'Barrière de lames',
                'description' => 'Crée une barrière de lames tournoyantes qui protège et attaque',
                'hit' => 90,
                'level' => 2,
            ],
            'silver_bolt' => [
                'slug' => 'silver-bolt',
                'damage' => 6,
                'element' => Element::Metal,
                'heal' => null,
                'name' => 'Carreau d\'argent',
                'description' => 'Un projectile d\'argent pur qui transperce les défenses',
                'hit' => 85,
                'level' => 3,
            ],
            'crushing_weight' => [
                'slug' => 'crushing-weight',
                'damage' => 7,
                'element' => Element::Metal,
                'heal' => null,
                'name' => 'Poids écrasant',
                'description' => 'Une masse métallique qui s\'abat sur l\'ennemi',
                'hit' => 80,
                'level' => 4,
            ],
            'magnetic_pull' => [
                'slug' => 'magnetic-pull',
                'damage' => 2,
                'element' => Element::Metal,
                'heal' => null,
                'name' => 'Attraction magnétique',
                'description' => 'Attire violemment les objets métalliques vers l\'ennemi',
                'hit' => 95,
                'level' => 1,
            ],

            // Sorts de nature
            'liana_whip' => [
                'slug' => 'liana-whip',
                'damage' => 1,
                'element' => Element::Beast,
                'heal' => null,
                'name' => 'Liane',
                'description' => 'Des lianes fouettent l\'ennemi',
                'hit' => 90,
                'energyCost' => 4,
                'level' => 1,
            ],
            'thorn_burst' => [
                'slug' => 'thorn-burst',
                'damage' => 3,
                'element' => Element::Beast,
                'heal' => null,
                'name' => 'Explosion d\'épines',
                'description' => 'Des épines jaillissent du sol et blessent les ennemis',
                'hit' => 85,
                'level' => 2,
            ],
            'natural_healing' => [
                'slug' => 'natural-healing',
                'damage' => null,
                'element' => Element::Beast,
                'heal' => 4,
                'name' => 'Guérison naturelle',
                'description' => 'Les forces de la nature soignent les blessures',
                'hit' => 100,
                'level' => 1,
            ],
            'poison_cloud' => [
                'slug' => 'poison-cloud',
                'damage' => 4,
                'element' => Element::Beast,
                'heal' => null,
                'name' => 'Empoisonnement',
                'description' => 'Un nuage de spores toxiques qui empoisonne l\'ennemi',
                'hit' => 85,
                'energyCost' => 10,
                'statusEffectSlug' => 'poison',
                'level' => 3,
            ],
            'entangling_roots' => [
                'slug' => 'entangling-roots',
                'damage' => 2,
                'element' => Element::Beast,
                'heal' => null,
                'name' => 'Racines enchevetrees',
                'description' => 'Des racines surgissent du sol et immobilisent l\'ennemi',
                'hit' => 95,
                'statusEffectSlug' => 'paralysis',
                'level' => 2,
            ],
            'nature_wrath' => [
                'slug' => 'nature-wrath',
                'damage' => 6,
                'element' => Element::Beast,
                'heal' => null,
                'name' => 'Appel de la foret',
                'description' => 'Dechaine la fureur de la nature sur l\'ennemi',
                'hit' => 80,
                'energyCost' => 20,
                'cooldown' => 3,
                'statusEffectSlug' => 'poison-strong',
                'aoeTargets' => 0,
                'level' => 4,
            ],
            'leaf_blade' => [
                'slug' => 'leaf-blade',
                'damage' => 5,
                'element' => Element::Beast,
                'heal' => null,
                'name' => 'Lame feuille',
                'description' => 'Une lame tranchante formée de feuilles acérées',
                'hit' => 90,
                'level' => 3,
            ],
            'forest_embrace' => [
                'slug' => 'forest-embrace',
                'damage' => null,
                'element' => Element::Beast,
                'heal' => 7,
                'name' => 'Étreinte de la forêt',
                'description' => 'L\'énergie de la forêt enveloppe et soigne les blessures',
                'hit' => 100,
                'level' => 3,
            ],
            'venomous_bite' => [
                'slug' => 'venomous-bite',
                'damage' => 3,
                'element' => Element::Beast,
                'heal' => null,
                'name' => 'Morsure venimeuse',
                'description' => 'Une morsure qui injecte un venin puissant',
                'hit' => 90,
                'level' => 2,
            ],
            'wild_growth' => [
                'slug' => 'wild-growth',
                'damage' => 1,
                'element' => Element::Beast,
                'heal' => 5,
                'name' => 'Croissance sauvage',
                'description' => 'Des plantes médicinales poussent rapidement et soignent les blessures',
                'hit' => 100,
                'level' => 2,
            ],
            'nature_fury' => [
                'slug' => 'nature-fury',
                'damage' => 8,
                'element' => Element::Beast,
                'heal' => null,
                'name' => 'Fureur naturelle',
                'description' => 'Libère toute la puissance destructrice de la nature',
                'hit' => 75,
                'level' => 5,
            ],
            'thorn_shield' => [
                'slug' => 'thorn-shield',
                'damage' => 2,
                'element' => Element::Beast,
                'heal' => 3,
                'name' => 'Bouclier d\'épines',
                'description' => 'Un bouclier d\'épines qui protège et blesse les attaquants',
                'hit' => 100,
                'level' => 2,
            ],
            'toxic_spores' => [
                'slug' => 'toxic-spores',
                'damage' => 4,
                'element' => Element::Beast,
                'heal' => null,
                'name' => 'Spores toxiques',
                'description' => 'Libère des spores hautement toxiques dans l\'air',
                'hit' => 85,
                'level' => 2,
            ],
            'nature_blessing' => [
                'slug' => 'nature-blessing',
                'damage' => null,
                'element' => Element::Beast,
                'heal' => 10,
                'name' => 'Bénédiction de la nature',
                'description' => 'La bénédiction de la nature qui restaure la vitalité',
                'hit' => 100,
                'level' => 4,
            ],
            'vine_snare' => [
                'slug' => 'vine-snare',
                'damage' => 3,
                'element' => Element::Beast,
                'heal' => null,
                'name' => 'Piège de vignes',
                'description' => 'Des vignes surgissent et s\'enroulent autour de l\'ennemi',
                'hit' => 90,
                'level' => 2,
            ],
            'primal_surge' => [
                'slug' => 'primal-surge',
                'damage' => 5,
                'element' => Element::Beast,
                'heal' => 5,
                'name' => 'Afflux primordial',
                'description' => 'Un afflux d\'énergie primordiale qui soigne et blesse',
                'hit' => 85,
                'level' => 4,
            ],

            // Sorts de vent
            'wind_lame' => [
                'slug' => 'wind-lame',
                'damage' => 1,
                'element' => Element::Air,
                'heal' => null,
                'name' => "Lame d'air",
                'description' => "une lame d'air tranchante",
                'hit' => 90,
                'level' => 1,
            ],
            'tornado' => [
                'slug' => 'tornado',
                'damage' => 4,
                'element' => Element::Air,
                'heal' => null,
                'name' => 'Tornade',
                'description' => 'Une violente tornade qui emporte tout sur son passage',
                'hit' => 80,
                'level' => 2,
            ],
            'wind_shield' => [
                'slug' => 'wind-shield',
                'damage' => 0,
                'element' => Element::Air,
                'heal' => 2,
                'name' => 'Bouclier de vent',
                'description' => 'Un tourbillon protecteur qui dévie les attaques',
                'hit' => 100,
                'level' => 1,
            ],
            'gust' => [
                'slug' => 'gust',
                'damage' => 2,
                'element' => Element::Air,
                'heal' => null,
                'name' => 'Bourrasque',
                'description' => 'Une puissante bourrasque qui repousse l\'ennemi',
                'hit' => 95,
                'level' => 1,
            ],
            'air_dash' => [
                'slug' => 'air-dash',
                'damage' => 1,
                'element' => Element::Air,
                'heal' => 1,
                'name' => 'Ruée d\'air',
                'description' => 'Permet de se déplacer rapidement sur un coussin d\'air',
                'hit' => 100,
                'level' => 1,
            ],
            'air_slash' => [
                'slug' => 'air-slash',
                'damage' => 5,
                'element' => Element::Air,
                'heal' => null,
                'name' => 'Tranchant aérien',
                'description' => 'Une lame d\'air comprimé qui tranche l\'ennemi',
                'hit' => 85,
                'level' => 3,
            ],
            'cyclone' => [
                'slug' => 'cyclone',
                'damage' => 6,
                'element' => Element::Air,
                'heal' => null,
                'name' => 'Cyclone',
                'description' => 'Un puissant cyclone qui déchire tout sur son passage',
                'hit' => 80,
                'level' => 3,
            ],
            'wind_blast' => [
                'slug' => 'wind-blast',
                'damage' => 3,
                'element' => Element::Air,
                'heal' => null,
                'name' => 'Souffle du vent',
                'description' => 'Une rafale concentrée qui frappe l\'ennemi',
                'hit' => 90,
                'level' => 2,
            ],
            'healing_breeze' => [
                'slug' => 'healing-breeze',
                'damage' => null,
                'element' => Element::Air,
                'heal' => 5,
                'name' => 'Brise guérisseuse',
                'description' => 'Une douce brise qui apaise et soigne les blessures',
                'hit' => 100,
                'level' => 2,
            ],
            'vacuum_blade' => [
                'slug' => 'vacuum-blade',
                'damage' => 7,
                'element' => Element::Air,
                'heal' => null,
                'name' => 'Lame de vide',
                'description' => 'Une lame créée par le vide qui tranche tout',
                'hit' => 75,
                'level' => 4,
            ],
            'wind_wall' => [
                'slug' => 'wind-wall',
                'damage' => 1,
                'element' => Element::Air,
                'heal' => 4,
                'name' => 'Mur de vent',
                'description' => 'Un mur de vent qui protège et repousse les attaques',
                'hit' => 100,
                'level' => 2,
            ],
            'hurricane' => [
                'slug' => 'hurricane',
                'damage' => 8,
                'element' => Element::Air,
                'heal' => null,
                'name' => 'Ouragan',
                'description' => 'Un ouragan dévastateur qui ravage tout',
                'hit' => 70,
                'level' => 5,
            ],
            'air_current' => [
                'slug' => 'air-current',
                'damage' => 2,
                'element' => Element::Air,
                'heal' => 3,
                'name' => 'Courant d\'air',
                'description' => 'Un courant d\'air revigorant qui soigne et protège',
                'hit' => 95,
                'level' => 1,
            ],
            'pressure_point' => [
                'slug' => 'pressure-point',
                'damage' => 4,
                'element' => Element::Air,
                'heal' => null,
                'name' => 'Point de pression',
                'description' => 'Concentre l\'air sur un point précis pour causer des dégâts internes',
                'hit' => 90,
                'level' => 2,
            ],
            'wind_scythe' => [
                'slug' => 'wind-scythe',
                'damage' => 6,
                'element' => Element::Air,
                'heal' => null,
                'name' => 'Faux de vent',
                'description' => 'Une faux d\'air tranchante qui fauche les ennemis',
                'hit' => 85,
                'level' => 3,
            ],
            'tempest' => [
                'slug' => 'tempest',
                'damage' => 5,
                'element' => Element::Air,
                'heal' => null,
                'name' => 'Tempête',
                'description' => 'Une violente tempête qui frappe de toutes parts',
                'hit' => 85,
                'level' => 3,
            ],
            'wind_blessing' => [
                'slug' => 'wind-blessing',
                'damage' => null,
                'element' => Element::Air,
                'heal' => 7,
                'name' => 'Bénédiction du vent',
                'description' => 'La bénédiction des vents qui soigne et revigore',
                'hit' => 100,
                'level' => 3,
            ],

            // Sorts d'eau
            'water_jet' => [
                'slug' => 'water-jet',
                'damage' => 2,
                'element' => Element::Water,
                'heal' => null,
                'name' => 'Jet d\'eau',
                'description' => 'Un jet d\'eau sous pression qui frappe l\'ennemi',
                'hit' => 90,
                'energyCost' => 4,
                'level' => 1,
            ],
            'tidal_wave' => [
                'slug' => 'tidal-wave',
                'damage' => 5,
                'element' => Element::Water,
                'heal' => null,
                'name' => 'Raz-de-marée',
                'description' => 'Une vague massive qui submerge les ennemis',
                'hit' => 80,
                'energyCost' => 12,
                'aoeTargets' => 0,
                'level' => 3,
            ],
            'frost_bolt' => [
                'slug' => 'frost-bolt',
                'damage' => 3,
                'element' => Element::Water,
                'heal' => null,
                'name' => 'Trait de givre',
                'description' => 'Un projectile de glace qui ralentit la cible',
                'hit' => 90,
                'statusEffectSlug' => 'paralysis',
                'level' => 2,
            ],
            'aqua_shield' => [
                'slug' => 'aqua-shield',
                'damage' => 0,
                'element' => Element::Water,
                'heal' => 4,
                'name' => 'Bouclier aquatique',
                'description' => 'Un bouclier d\'eau qui absorbe les coups',
                'hit' => 100,
                'energyCost' => 6,
                'statusEffectSlug' => 'shield',
                'level' => 1,
            ],
            'tsunami' => [
                'slug' => 'tsunami',
                'damage' => 8,
                'element' => Element::Water,
                'heal' => null,
                'name' => 'Tsunami',
                'description' => 'Un tsunami dévastateur qui engloutit tout',
                'hit' => 70,
                'energyCost' => 25,
                'cooldown' => 4,
                'aoeTargets' => 0,
                'critical' => 12,
                'level' => 5,
            ],
            'maelstrom' => [
                'slug' => 'maelstrom',
                'damage' => 6,
                'element' => Element::Water,
                'heal' => null,
                'name' => 'Maelström',
                'description' => 'Un tourbillon aquatique qui aspire et blesse les ennemis',
                'hit' => 80,
                'energyCost' => 15,
                'cooldown' => 3,
                'aoeTargets' => 0,
                'level' => 4,
            ],
            'water_heal' => [
                'slug' => 'water-heal',
                'damage' => null,
                'element' => Element::Water,
                'heal' => 5,
                'name' => 'Soin aquatique',
                'description' => 'L\'eau purificatrice soigne les blessures',
                'hit' => 100,
                'energyCost' => 5,
                'level' => 1,
            ],
            'mist_veil' => [
                'slug' => 'mist-veil',
                'damage' => null,
                'element' => Element::Water,
                'heal' => 6,
                'name' => 'Voile de brume',
                'description' => 'Une brume protectrice qui soigne et cache',
                'hit' => 100,
                'energyCost' => 8,
                'statusEffectSlug' => 'shield',
                'level' => 2,
            ],
            'ice_lance' => [
                'slug' => 'ice-lance',
                'damage' => 4,
                'element' => Element::Water,
                'heal' => null,
                'name' => 'Lance de glace',
                'description' => 'Une lance de glace qui transperce l\'ennemi',
                'hit' => 85,
                'energyCost' => 8,
                'critical' => 10,
                'level' => 2,
            ],
            'water_prison' => [
                'slug' => 'water-prison',
                'damage' => 3,
                'element' => Element::Water,
                'heal' => null,
                'name' => 'Prison d\'eau',
                'description' => 'Emprisonne l\'ennemi dans une sphère d\'eau',
                'hit' => 90,
                'statusEffectSlug' => 'paralysis',
                'level' => 3,
            ],
            'ocean_blessing' => [
                'slug' => 'ocean-blessing',
                'damage' => null,
                'element' => Element::Water,
                'heal' => 10,
                'name' => 'Bénédiction de l\'océan',
                'description' => 'Les eaux sacrées restaurent profondément la vitalité',
                'hit' => 100,
                'energyCost' => 15,
                'statusEffectSlug' => 'regeneration',
                'level' => 4,
            ],
            'ice_storm' => [
                'slug' => 'ice-storm',
                'damage' => 5,
                'element' => Element::Water,
                'heal' => null,
                'name' => 'Tempête de glace',
                'description' => 'Une tempête de grêle et de glace qui martèle la zone',
                'hit' => 80,
                'energyCost' => 14,
                'aoeTargets' => 0,
                'level' => 3,
            ],
            'bubble_shield' => [
                'slug' => 'bubble-shield',
                'damage' => 0,
                'element' => Element::Water,
                'heal' => 8,
                'name' => 'Bulle protectrice',
                'description' => 'Une bulle d\'eau qui protège des attaques',
                'hit' => 100,
                'energyCost' => 12,
                'statusEffectSlug' => 'shield-strong',
                'level' => 3,
            ],
            'torrent' => [
                'slug' => 'torrent',
                'damage' => 4,
                'element' => Element::Water,
                'heal' => null,
                'name' => 'Torrent',
                'description' => 'Un torrent d\'eau qui emporte tout sur son passage',
                'hit' => 85,
                'level' => 2,
            ],
            'frozen_touch' => [
                'slug' => 'frozen-touch',
                'damage' => 2,
                'element' => Element::Water,
                'heal' => null,
                'name' => 'Toucher glacé',
                'description' => 'Un toucher qui gèle la cible au contact',
                'hit' => 95,
                'level' => 1,
            ],
            'rising_tide' => [
                'slug' => 'rising-tide',
                'damage' => 1,
                'element' => Element::Water,
                'heal' => 3,
                'name' => 'Marée montante',
                'description' => 'La marée monte et soigne les alliés tout en repoussant les ennemis',
                'hit' => 95,
                'level' => 2,
            ],

            // Sorts spécifiques — Berserker (feu/physique)
            'rage_flame' => [
                'slug' => 'rage-flame',
                'damage' => 3,
                'element' => Element::Fire,
                'heal' => null,
                'name' => 'Flamme de rage',
                'description' => 'La rage intérieure se transforme en flammes destructrices',
                'hit' => 95,
                'energyCost' => 6,
                'critical' => 15,
                'level' => 2,
            ],
            'berserk_charge' => [
                'slug' => 'berserk-charge',
                'damage' => 4,
                'element' => Element::Fire,
                'heal' => null,
                'name' => 'Charge enflammée',
                'description' => 'Une charge furieuse enveloppée de flammes',
                'hit' => 90,
                'energyCost' => 10,
                'critical' => 12,
                'level' => 3,
            ],
            'fury_strike' => [
                'slug' => 'fury-strike',
                'damage' => 6,
                'element' => Element::Fire,
                'heal' => null,
                'name' => 'Frappe de furie',
                'description' => 'Un coup dévastateur porté par une rage incontrôlable',
                'hit' => 80,
                'energyCost' => 15,
                'critical' => 18,
                'level' => 4,
            ],
            'blood_fury' => [
                'slug' => 'blood-fury',
                'damage' => 9,
                'element' => Element::Fire,
                'heal' => null,
                'name' => 'Furie sanguinaire',
                'description' => 'La rage atteint son paroxysme, déchaînant une puissance dévastatrice',
                'hit' => 75,
                'energyCost' => 25,
                'cooldown' => 4,
                'critical' => 20,
                'level' => 5,
            ],

            // Sorts spécifiques — Artificier (feu/pièges)
            'fire_trap' => [
                'slug' => 'fire-trap',
                'damage' => 3,
                'element' => Element::Fire,
                'heal' => null,
                'name' => 'Piège incendiaire',
                'description' => 'Pose un piège qui explose en flammes au contact',
                'hit' => 95,
                'energyCost' => 6,
                'statusEffectSlug' => 'burn',
                'level' => 2,
            ],
            'explosive_mine' => [
                'slug' => 'explosive-mine',
                'damage' => 5,
                'element' => Element::Fire,
                'heal' => null,
                'name' => 'Mine explosive',
                'description' => 'Une mine qui explose violemment au contact',
                'hit' => 90,
                'energyCost' => 10,
                'aoeTargets' => 0,
                'level' => 3,
            ],
            'flash_bomb' => [
                'slug' => 'flash-bomb',
                'damage' => 2,
                'element' => Element::Fire,
                'heal' => null,
                'name' => 'Bombe flash',
                'description' => 'Une bombe aveuglante qui désoriente les ennemis',
                'hit' => 100,
                'statusEffectSlug' => 'paralysis',
                'level' => 2,
            ],
            'artillery_barrage' => [
                'slug' => 'artillery-barrage',
                'damage' => 8,
                'element' => Element::Fire,
                'heal' => null,
                'name' => 'Barrage d\'artillerie',
                'description' => 'Un bombardement massif qui dévaste la zone',
                'hit' => 70,
                'energyCost' => 22,
                'cooldown' => 4,
                'aoeTargets' => 0,
                'critical' => 10,
                'level' => 5,
            ],

            // Sorts spécifiques — Archer (air/physique distance)
            'precise_shot' => [
                'slug' => 'precise-shot',
                'damage' => 2,
                'element' => Element::Air,
                'heal' => null,
                'name' => 'Tir précis',
                'description' => 'Un tir soigneusement ajusté qui touche à coup sûr',
                'hit' => 100,
                'energyCost' => 4,
                'critical' => 12,
                'level' => 1,
            ],
            'arrow_rain' => [
                'slug' => 'arrow-rain',
                'damage' => 4,
                'element' => Element::Air,
                'heal' => null,
                'name' => 'Pluie de flèches',
                'description' => 'Une pluie de flèches qui s\'abat sur la zone',
                'hit' => 80,
                'energyCost' => 12,
                'aoeTargets' => 0,
                'level' => 3,
            ],
            'critical_shot' => [
                'slug' => 'critical-shot',
                'damage' => 6,
                'element' => Element::Air,
                'heal' => null,
                'name' => 'Tir critique',
                'description' => 'Un tir visant les points faibles de l\'ennemi',
                'hit' => 85,
                'energyCost' => 10,
                'critical' => 25,
                'level' => 3,
            ],
            'piercing_arrow' => [
                'slug' => 'piercing-arrow',
                'damage' => 8,
                'element' => Element::Air,
                'heal' => null,
                'name' => 'Flèche perforante',
                'description' => 'Une flèche qui transperce les armures les plus solides',
                'hit' => 80,
                'energyCost' => 18,
                'cooldown' => 3,
                'critical' => 15,
                'level' => 5,
            ],

            // Sorts spécifiques — Chevalier (métal/tank)
            'provocation' => [
                'slug' => 'provocation',
                'damage' => 1,
                'element' => Element::Metal,
                'heal' => null,
                'name' => 'Provocation',
                'description' => 'Provoque l\'ennemi, attirant son attention',
                'hit' => 100,
                'energyCost' => 3,
                'level' => 1,
            ],
            'riposte' => [
                'slug' => 'riposte',
                'damage' => 4,
                'element' => Element::Metal,
                'heal' => 2,
                'name' => 'Riposte',
                'description' => 'Contre-attaque après une parade réussie',
                'hit' => 95,
                'energyCost' => 8,
                'level' => 2,
            ],
            'steel_fortress' => [
                'slug' => 'steel-fortress',
                'damage' => 0,
                'element' => Element::Metal,
                'heal' => 10,
                'name' => 'Forteresse d\'acier',
                'description' => 'Se transforme en forteresse imprenable',
                'hit' => 100,
                'energyCost' => 20,
                'cooldown' => 4,
                'statusEffectSlug' => 'shield-strong',
                'level' => 5,
            ],

            // Sorts spécifiques — Ingénieur (métal/support)
            'turret' => [
                'slug' => 'turret',
                'damage' => 3,
                'element' => Element::Metal,
                'heal' => null,
                'name' => 'Tourelle',
                'description' => 'Déploie une tourelle métallique qui tire sur l\'ennemi',
                'hit' => 85,
                'energyCost' => 8,
                'level' => 2,
            ],
            'repair_bot' => [
                'slug' => 'repair-bot',
                'damage' => null,
                'element' => Element::Metal,
                'heal' => 6,
                'name' => 'Automate réparateur',
                'description' => 'Un petit automate qui répare les blessures',
                'hit' => 100,
                'energyCost' => 10,
                'level' => 3,
            ],
            'siege_engine' => [
                'slug' => 'siege-engine',
                'damage' => 7,
                'element' => Element::Metal,
                'heal' => null,
                'name' => 'Engin de siège',
                'description' => 'Déploie un puissant engin de siège',
                'hit' => 80,
                'energyCost' => 20,
                'cooldown' => 4,
                'aoeTargets' => 0,
                'level' => 5,
            ],

            // Sorts spécifiques — Chasseur (bête/distance)
            'falcon_strike' => [
                'slug' => 'falcon-strike',
                'damage' => 2,
                'element' => Element::Beast,
                'heal' => null,
                'name' => 'Appel du faucon',
                'description' => 'Un faucon fond sur l\'ennemi depuis les cieux',
                'hit' => 95,
                'energyCost' => 5,
                'level' => 1,
            ],
            'bear_trap' => [
                'slug' => 'bear-trap',
                'damage' => 3,
                'element' => Element::Beast,
                'heal' => null,
                'name' => 'Piège à ours',
                'description' => 'Un piège qui immobilise et blesse la cible',
                'hit' => 90,
                'energyCost' => 7,
                'statusEffectSlug' => 'paralysis',
                'level' => 2,
            ],
            'poison_arrow' => [
                'slug' => 'poison-arrow',
                'damage' => 4,
                'element' => Element::Beast,
                'heal' => null,
                'name' => 'Tir empoisonné',
                'description' => 'Une flèche enduite de poison qui affaiblit la cible',
                'hit' => 85,
                'energyCost' => 9,
                'statusEffectSlug' => 'poison',
                'level' => 3,
            ],
            'pack_hunt' => [
                'slug' => 'pack-hunt',
                'damage' => 7,
                'element' => Element::Beast,
                'heal' => null,
                'name' => 'Chasse en meute',
                'description' => 'Appelle la meute pour une attaque coordonnée',
                'hit' => 80,
                'energyCost' => 20,
                'cooldown' => 4,
                'aoeTargets' => 0,
                'level' => 5,
            ],

            // Sorts spécifiques — Dompteur (bête/tank invocateur)
            'beast_bond' => [
                'slug' => 'beast-bond',
                'damage' => 1,
                'element' => Element::Beast,
                'heal' => 3,
                'name' => 'Lien bestial',
                'description' => 'Crée un lien avec une bête qui protège et soigne',
                'hit' => 100,
                'energyCost' => 5,
                'level' => 1,
            ],
            'savage_charge' => [
                'slug' => 'savage-charge',
                'damage' => 4,
                'element' => Element::Beast,
                'heal' => null,
                'name' => 'Charge sauvage',
                'description' => 'La bête liée charge furieusement l\'ennemi',
                'hit' => 90,
                'energyCost' => 10,
                'critical' => 12,
                'level' => 3,
            ],
            'alpha_roar' => [
                'slug' => 'alpha-roar',
                'damage' => 2,
                'element' => Element::Beast,
                'heal' => 5,
                'name' => 'Rugissement alpha',
                'description' => 'Un rugissement qui terrifie les ennemis et renforce les alliés',
                'hit' => 95,
                'energyCost' => 12,
                'statusEffectSlug' => 'paralysis',
                'level' => 4,
            ],

            // Sorts spécifiques — Paladin (lumière/tank healer)
            'sacred_strike' => [
                'slug' => 'sacred-strike',
                'damage' => 3,
                'element' => Element::Light,
                'heal' => 2,
                'name' => 'Frappe sacrée',
                'description' => 'Un coup béni qui blesse et purifie',
                'hit' => 90,
                'energyCost' => 6,
                'level' => 2,
            ],
            'light_aura' => [
                'slug' => 'light-aura',
                'damage' => 0,
                'element' => Element::Light,
                'heal' => 4,
                'name' => 'Aura de lumière',
                'description' => 'Une aura protectrice qui soigne continuellement',
                'hit' => 100,
                'energyCost' => 8,
                'statusEffectSlug' => 'regeneration',
                'level' => 2,
            ],
            'divine_judgment' => [
                'slug' => 'divine-judgment',
                'damage' => 7,
                'element' => Element::Light,
                'heal' => 3,
                'name' => 'Jugement divin',
                'description' => 'La lumière divine frappe les impurs et guérit les justes',
                'hit' => 85,
                'energyCost' => 20,
                'cooldown' => 4,
                'critical' => 12,
                'level' => 5,
            ],

            // Sorts spécifiques — Prêtre (lumière/heal pur)
            'prayer' => [
                'slug' => 'prayer',
                'damage' => null,
                'element' => Element::Light,
                'heal' => 6,
                'name' => 'Prière',
                'description' => 'Une prière fervente qui restaure la santé',
                'hit' => 100,
                'energyCost' => 7,
                'level' => 2,
            ],
            'miracle' => [
                'slug' => 'miracle',
                'damage' => null,
                'element' => Element::Light,
                'heal' => 15,
                'name' => 'Miracle',
                'description' => 'Un miracle divin qui restaure massivement la santé',
                'hit' => 100,
                'energyCost' => 25,
                'cooldown' => 5,
                'statusEffectSlug' => 'regeneration-strong',
                'level' => 5,
            ],

            // Sorts spécifiques — Inquisiteur (lumière/DPS)
            'smite' => [
                'slug' => 'smite',
                'damage' => 3,
                'element' => Element::Light,
                'heal' => null,
                'name' => 'Châtiment sacré',
                'description' => 'Frappe l\'ennemi avec la colère divine',
                'hit' => 90,
                'energyCost' => 6,
                'level' => 2,
            ],
            'holy_fire' => [
                'slug' => 'holy-fire',
                'damage' => 5,
                'element' => Element::Light,
                'heal' => null,
                'name' => 'Feu sacré',
                'description' => 'Des flammes sacrées qui brûlent les impurs',
                'hit' => 85,
                'energyCost' => 10,
                'statusEffectSlug' => 'burn',
                'level' => 3,
            ],
            'divine_sentence' => [
                'slug' => 'divine-sentence',
                'damage' => 8,
                'element' => Element::Light,
                'heal' => null,
                'name' => 'Sentence divine',
                'description' => 'Le jugement final frappe l\'hérétique sans pitié',
                'hit' => 80,
                'energyCost' => 22,
                'cooldown' => 4,
                'critical' => 15,
                'level' => 5,
            ],

            // Sorts spécifiques — Assassin (ombre/CaC furtif)
            'ambush' => [
                'slug' => 'ambush',
                'damage' => 3,
                'element' => Element::Dark,
                'heal' => null,
                'name' => 'Embuscade',
                'description' => 'Surgit de l\'ombre pour frapper par surprise',
                'hit' => 95,
                'energyCost' => 5,
                'critical' => 20,
                'level' => 2,
            ],
            'deadly_strike' => [
                'slug' => 'deadly-strike',
                'damage' => 6,
                'element' => Element::Dark,
                'heal' => null,
                'name' => 'Coup mortel',
                'description' => 'Un coup visant les organes vitaux',
                'hit' => 80,
                'energyCost' => 12,
                'critical' => 25,
                'level' => 4,
            ],
            'shadow_dance' => [
                'slug' => 'shadow-dance',
                'damage' => 8,
                'element' => Element::Dark,
                'heal' => null,
                'name' => 'Danse des ombres',
                'description' => 'Se fond dans les ombres pour porter une série de coups mortels',
                'hit' => 85,
                'energyCost' => 20,
                'cooldown' => 4,
                'critical' => 20,
                'level' => 5,
            ],

            // Sorts spécifiques — Sorcier (ombre/debuff)
            'hex' => [
                'slug' => 'hex',
                'damage' => 2,
                'element' => Element::Dark,
                'heal' => null,
                'name' => 'Maléfice',
                'description' => 'Un maléfice qui affaiblit la cible',
                'hit' => 95,
                'energyCost' => 5,
                'statusEffectSlug' => 'poison',
                'level' => 1,
            ],
            'terror' => [
                'slug' => 'terror',
                'damage' => 3,
                'element' => Element::Dark,
                'heal' => null,
                'name' => 'Terreur',
                'description' => 'Plonge l\'ennemi dans une terreur paralysante',
                'hit' => 90,
                'energyCost' => 8,
                'statusEffectSlug' => 'paralysis',
                'level' => 3,
            ],
            'dark_pact' => [
                'slug' => 'dark-pact',
                'damage' => 7,
                'element' => Element::Dark,
                'heal' => 3,
                'name' => 'Pacte sombre',
                'description' => 'Scelle un pacte avec les ténèbres, sacrifiant sa vie pour du pouvoir',
                'hit' => 85,
                'energyCost' => 18,
                'cooldown' => 4,
                'critical' => 12,
                'level' => 5,
            ],

            // Sorts spécifiques — Vagabond (air/support)
            'haste' => [
                'slug' => 'haste',
                'damage' => null,
                'element' => Element::Air,
                'heal' => 3,
                'name' => 'Hâte',
                'description' => 'Accélère les mouvements et restaure un peu d\'énergie',
                'hit' => 100,
                'energyCost' => 5,
                'level' => 1,
            ],
            'mirage' => [
                'slug' => 'mirage',
                'damage' => 2,
                'element' => Element::Air,
                'heal' => 2,
                'name' => 'Mirage',
                'description' => 'Crée des illusions qui désorientent l\'ennemi',
                'hit' => 90,
                'energyCost' => 7,
                'level' => 2,
            ],
            'zephyr' => [
                'slug' => 'zephyr',
                'damage' => null,
                'element' => Element::Air,
                'heal' => 8,
                'name' => 'Zéphyr',
                'description' => 'Un vent doux et chaud qui revigore profondément',
                'hit' => 100,
                'energyCost' => 15,
                'statusEffectSlug' => 'regeneration',
                'level' => 4,
            ],

            // Sorts spécifiques — Gardien (terre/tank support)
            'shared_shield' => [
                'slug' => 'shared-shield',
                'damage' => 0,
                'element' => Element::Earth,
                'heal' => 5,
                'name' => 'Bouclier partagé',
                'description' => 'Un bouclier de roche qui protège le groupe',
                'hit' => 100,
                'energyCost' => 10,
                'statusEffectSlug' => 'shield',
                'level' => 2,
            ],
            'bastion' => [
                'slug' => 'bastion',
                'damage' => 0,
                'element' => Element::Earth,
                'heal' => 12,
                'name' => 'Bastion',
                'description' => 'Érige un bastion de pierre indestructible',
                'hit' => 100,
                'energyCost' => 25,
                'cooldown' => 5,
                'statusEffectSlug' => 'shield-strong',
                'level' => 5,
            ],

            // Sorts de consommables
            'beer_heal' => [
                'slug' => 'beer-heal',
                'damage' => null,
                'element' => Element::None,
                'heal' => 3,
                'name' => 'Gorgée de bière',
                'description' => 'Une bonne chope de bière qui réchauffe et revigore',
                'hit' => 100,
                'level' => 1,
            ],
            'mushroom_heal' => [
                'slug' => 'mushroom-heal',
                'damage' => null,
                'element' => Element::Beast,
                'heal' => 1,
                'name' => 'Champignon comestible',
                'description' => 'Un champignon aux vertus curatives... ou pas',
                'hit' => 100,
                'level' => 1,
            ],
            'potion_heal_major' => [
                'slug' => 'potion-heal-major',
                'damage' => null,
                'element' => Element::None,
                'heal' => 15,
                'name' => 'Soin majeur',
                'description' => 'Une puissante potion qui restaure une grande quantité de points de vie',
                'hit' => 100,
                'level' => 1,
            ],
            'antidote_heal' => [
                'slug' => 'antidote-heal',
                'damage' => null,
                'element' => Element::None,
                'heal' => 3,
                'name' => 'Antidote',
                'description' => 'Un remède qui purifie le corps et soigne légèrement',
                'hit' => 100,
                'level' => 1,
            ],
            'bread_heal' => [
                'slug' => 'bread-heal',
                'damage' => null,
                'element' => Element::None,
                'heal' => 4,
                'name' => 'Pain nourrissant',
                'description' => 'Un morceau de pain qui redonne des forces',
                'hit' => 100,
                'level' => 1,
            ],
            'grilled_meat_heal' => [
                'slug' => 'grilled-meat-heal',
                'damage' => null,
                'element' => Element::None,
                'heal' => 8,
                'name' => 'Viande revigorante',
                'description' => 'Une viande grillée à point qui revigore le corps',
                'hit' => 100,
                'level' => 1,
            ],
            'stew_heal' => [
                'slug' => 'stew-heal',
                'damage' => null,
                'element' => Element::None,
                'heal' => 12,
                'name' => 'Ragoût reconstituant',
                'description' => 'Un copieux ragoût qui restaure profondément le corps et l\'esprit',
                'hit' => 100,
                'level' => 1,
            ],

            // Sorts sans élément
            'none_attack_1' => [
                'slug' => 'none-attack-1',
                'damage' => 1,
                'element' => Element::None,
                'heal' => null,
                'name' => 'Attaque',
                'description' => 'Attaque 1',
                'hit' => 90,
                'level' => 1,
            ],
            'none_attack_2' => [
                'slug' => 'none-attack-2',
                'damage' => 2,
                'element' => Element::None,
                'heal' => null,
                'name' => 'Attaque',
                'description' => 'Attaque 2',
                'hit' => 90,
                'level' => 1,
            ],
            'none_attack_3' => [
                'slug' => 'none-attack-3',
                'damage' => 3,
                'element' => Element::None,
                'heal' => null,
                'name' => 'Attaque',
                'description' => 'Attaque 3',
                'hit' => 90,
                'level' => 1,
            ],
            'none_heal_2' => [
                'slug' => 'none-heal-2',
                'damage' => null,
                'element' => Element::None,
                'heal' => 2,
                'name' => 'Soin',
                'description' => 'Soin 2',
                'hit' => 90,
                'level' => 1,
            ],

            // === Materia Tier 2 — 1 par élément ===

            // Eau — Brume glaciale
            'frost_mist' => [
                'slug' => 'frost-mist',
                'damage' => 2,
                'element' => Element::Water,
                'heal' => null,
                'name' => 'Brume glaciale',
                'description' => 'Un brouillard de givre qui engourdit la cible',
                'hit' => 85,
                'energyCost' => 8,
                'statusEffectSlug' => 'paralysis',
                'level' => 2,
            ],
            // Air — Éclair en chaîne
            'air_chain_lightning' => [
                'slug' => 'air-chain-lightning',
                'damage' => 4,
                'element' => Element::Air,
                'heal' => null,
                'name' => 'Éclair en chaîne',
                'description' => 'Des éclairs qui rebondissent entre les ennemis',
                'hit' => 85,
                'energyCost' => 10,
                'aoeTargets' => 0,
                'level' => 2,
            ],
            // Terre — Mur de pierre
            'stone_shield' => [
                'slug' => 'stone-shield',
                'damage' => 0,
                'element' => Element::Earth,
                'heal' => 5,
                'name' => 'Mur de pierre',
                'description' => 'Érige un mur de pierre qui protège des attaques',
                'hit' => 100,
                'energyCost' => 10,
                'cooldown' => 3,
                'statusEffectSlug' => 'shield',
                'level' => 2,
            ],
            // Métal — Riposte d'acier
            'steel_riposte' => [
                'slug' => 'steel-riposte',
                'damage' => 3,
                'element' => Element::Metal,
                'heal' => 2,
                'name' => 'Riposte d\'acier',
                'description' => 'Une contre-attaque métallique qui blesse et protège',
                'hit' => 95,
                'energyCost' => 8,
                'level' => 2,
            ],
            // Bête — Morsure sauvage
            'savage_bite' => [
                'slug' => 'savage-bite',
                'damage' => 4,
                'element' => Element::Beast,
                'heal' => null,
                'name' => 'Morsure sauvage',
                'description' => 'Une morsure féroce qui déchire la cible',
                'hit' => 90,
                'critical' => 12,
                'energyCost' => 7,
                'level' => 2,
            ],
            // Lumière — Bénédiction
            'light_blessing' => [
                'slug' => 'light-blessing',
                'damage' => null,
                'element' => Element::Light,
                'heal' => 8,
                'name' => 'Bénédiction',
                'description' => 'Une bénédiction de lumière qui restaure la santé',
                'hit' => 100,
                'energyCost' => 10,
                'level' => 2,
            ],
            // Ombre — Drain vital
            'vital_drain' => [
                'slug' => 'vital-drain',
                'damage' => 3,
                'element' => Element::Dark,
                'heal' => 2,
                'name' => 'Drain vital',
                'description' => 'Aspire la force vitale de l\'ennemi',
                'hit' => 85,
                'energyCost' => 8,
                'level' => 2,
            ],

            // === Sorts de boss de zone (tâche 66) ===
            // Gardien de la Forêt — Rugissement primordial (signature phase 2)
            'primordial_roar' => [
                'slug' => 'primordial-roar',
                'damage' => 7,
                'element' => Element::Beast,
                'heal' => null,
                'name' => 'Rugissement primordial',
                'description' => 'Un rugissement ancestral qui fait trembler la terre et paralyse de terreur',
                'hit' => 80,
                'cooldown' => 3,
                'statusEffectSlug' => 'paralysis',
                'aoeTargets' => 0,
                'critical' => 10,
                'level' => 5,
            ],
            // Seigneur de la Forge — Forge obscure (signature phase 3)
            'dark_forge_blast' => [
                'slug' => 'dark-forge-blast',
                'damage' => 9,
                'element' => Element::Metal,
                'heal' => null,
                'name' => 'Déflagration de la forge obscure',
                'description' => 'Libère une explosion de métal en fusion imprégné de ténèbres',
                'hit' => 75,
                'cooldown' => 4,
                'statusEffectSlug' => 'burn',
                'aoeTargets' => 0,
                'critical' => 15,
                'level' => 5,
            ],
        ];
    }
}
